# A full-featured PBX (for rural telephony, etc) based on Asterisk and FreePBX.
# 2019: Worked on Ubuntu 18.04, Debian 9 w/ Node.js 10.x, and seemingly RPi 3+.
# 2021-08-03: Attempts FreePBX 16 Beta -- as required w/ PHP 7.4 OS's for #2897

# pbx_install: False
# pbx_enabled: False

# asterisk_chan_dongle: False

# pbx_signaling_ports_chan_sip: 5160:5161
# pbx_signaling_ports_chan_pjsip: 5060
# pbx_data_ports: 10000:20000
# pbx_http_port: 83
#
# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

#pbx_installed: False

asterisk_url: http://downloads.asterisk.org/pub/telephony/asterisk/
asterisk_src_file: asterisk-18-current.tar.gz
asterisk_src_dir: /opt/iiab/asterisk

freepbx_url: http://mirror.freepbx.org/modules/packages/freepbx/7.4/
freepbx_src_file: freepbx-16.0-latest.tgz
freepbx_src_dir: /opt/iiab/freepbx
freepbx_install_dir: /var/www/html/freepbx

asterisk_db_host: localhost
asterisk_db_user: asterisk
asterisk_db_dbname: asterisk
asterisk_db_password: asterisk
asterisk_db_cdrdbname: asteriskcdrdb

chan_dongle_url: https://github.com/wdoekes/asterisk-chan-dongle/archive/
chan_dongle_src_file: master.zip
chan_dongle_src_dir: /opt/iiab/chan_dongle
