pbx_install: False
pbx_enabled: False
pbx_installed: False
asterisk_chan_dongle: False

asterisk_url: http://downloads.asterisk.org/pub/telephony/asterisk/
asterisk_src_file: asterisk-16-current.tar.gz
asterisk_src_dir: /opt/iiab/asterisk

freepbx_url: http://mirror.freepbx.org/modules/packages/freepbx/
freepbx_src_file: freepbx-15.0-latest.tgz
freepbx_src_dir: /opt/iiab/freepbx
freepbx_install_dir: /var/www/html/freepbx

chan_dongle_url: https://github.com/wdoekes/asterisk-chan-dongle/archive/
chan_dongle_src_file: master.zip
chan_dongle_src_dir: /opt/iiab/chan_dongle
