- name: Install NGINX required and helper packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx-extras
    - uwsgi
    - uwsgi-plugin-python3
    - php-fpm
    - libnginx-mod-http-subs-filter

- name: Add http server user to shadow group, so it can authenticate Admin Console
  user:
    name: "{{ apache_user }}"
    groups: shadow

- name: Remove NGINX default config /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: 'Install 4 files from template: /etc/nginx/server.conf, /etc/nginx/nginx.conf, /etc/{{ apache_service }}/ports.conf, /etc/systemd/system/uwsgi.service'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'roles/nginx/templates/server.conf.j2', dest: '/etc/nginx/server.conf' }
    - { src: 'roles/nginx/templates/nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'roles/nginx/templates/ports.conf.j2', dest: '/etc/{{ apache_service }}/ports.conf' }

# php stem extension is installed in role httpd
# here it is linked to php-fpm
- name: Create softlink 20-stem.ini to /etc/php/{{ php_version }}/mods-available/stem.ini
  file:
    src: "/etc/php/{{ php_version }}/mods-available/stem.ini"
    path: "/etc/php/{{ php_version }}/fpm/conf.d/20-stem.ini"
    state: link
  when: nginx_enabled

- name: Restart php{{ php_version }}-fpm service
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted
  when: nginx_enabled


# RECORD NGINX AS INSTALLED

- name: "Set 'nginx_installed: True'"
  set_fact:
    nginx_installed: True

- name: "Add 'nginx_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    dest: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^nginx_installed'
    line: 'nginx_installed: True'
