# If using Nextcloud intensively, consider setting nginx_high_php_limits in:
# /etc/iiab/local_vars.yml

# nextcloud_install: False
# nextcloud_enabled: False

# Configuration tips for IPv4 access controls and tuning RAM/resources:
# https://github.com/iiab/iiab/blob/master/roles/nextcloud/README.md

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

nextcloud_url: /nextcloud
nextcloud_prefix: "{{ doc_root }}"    # /library/www/html (WAS /opt)
nextcloud_data_dir: "{{ content_base }}/nextcloud/data"    # /library/nextcloud/data BUT NOT USED BY NEXTCLOUD AS OF 2020-02-15, so it defaults to /opt/nextcloud/data ??

# 2020-01-07: If installing IIAB often, download.nextcloud.com may throttle
# you to ~100 kbit/sec, delaying your IIAB install by an hour or more (#2112).
# The following line can avoid that: (but might install an older Nextcloud!)
# nextcloud_dl_url: http://d.iiab.io/packages/latest.tar.bz2
nextcloud_dl_url: https://download.nextcloud.com/server/releases/latest.tar.bz2

# We install on MySQL with these settings:
nextcloud_dbname: nextcloud
nextcloud_dbuser: nextcloud
nextcloud_dbpassword: nextcloudmysql

nextcloud_admin_user: 'Admin'
nextcloud_admin_password: 'changeme'

# 2019-09-04: UNUSED (due to changes in roles/nextcloud/templates/nextcloud.conf.j2)
nextcloud_required_ip: 10.0.0.0/8 192.168.0.0/16

# 2020-02-15: UNUSED at the time.  Legacy remains from Apache:
# nextcloud_allow_public_ips: True
