wordpress_install: True
wordpress_enabled: True

# For schools that use WordPress intensively.  WARNING: Enabling this (might)
# cause excess use of RAM or other resources?  github.com/iiab/iiab/issues/1147
wordpress_raise_php_limits: False

wordpress_download_base_url: https://wordpress.org
wordpress_src: latest.tar.gz

wp_db_name: iiab_wp
wp_db_user: iiab_wp
wp_db_user_password: changeme

wp_install_path: "{{ content_base }}"
#wp_install_path: /library

wp_abs_path: "{{ wp_install_path }}/wordpress"
#wp_abs_path: /library/wordpress

wp_url: /wordpress
wp_full_url: "http://{{ iiab_hostname }}{{ wp_url }}"
