wordpress_install: True
wordpress_enabled: True

# If using WordPress intensively, consider setting apache_raise_php_limits in:
# /etc/iiab/local_vars.yml

See iiab/iiab #1147
# WARNING: Enabling this (might) cause excess use of RAM or other resources?
apache_raise_php_limits: False
# roles/httpd/defaults/main.yml

wordpress_download_base_url: https://wordpress.org
wordpress_src: latest.tar.gz

wp_db_name: iiab_wp
wp_db_user: iiab_wp
wp_db_user_password: changeme

wp_install_path: "{{ content_base }}"
#wp_install_path: /library

wp_abs_path: "{{ wp_install_path }}/wordpress"
#wp_abs_path: /library/wordpress

wp_url: /wordpress
wp_full_url: "http://{{ iiab_hostname }}{{ wp_url }}"
