- name: Enable & Restart 'luanti-server' or 'minetest-server' service
  systemd:
    daemon_reload: yes
    name: "{{ luanti_systemd_unit }}"
    enabled: yes
    state: restarted
  when: luanti_enabled

- name: Disable & Stop 'luanti-server' or 'minetest-server' service
  systemd:
    daemon_reload: yes
    name: "{{ luanti_systemd_unit }}"
    enabled: no
    state: stopped
  when: not luanti_enabled
