- name: "Install Luanti package -- 'minetest-server' still works in 2025 -- as OS's transition to 'luanti-server'"
  package:
    name: minetest-server    # name: "{{ luanti_systemd_unit }}" coincidentally MIGHT work here too -- e.g. if Debian 13+, RasPiOS 13+, Ubuntu 25.10+ really all rename deb/apt package to 'luanti-server' ?
    state: present

- name: Add some parameters to {{ luanti_config_file }} that was automatically created
  lineinfile:
    path: "{{ luanti_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^server_name = ', line: 'server_name = Internet-in-a-Box Luanti Server' }
    - { regexp: '^name = ', line: 'name = {{ luanti_server_admin }}' }
    - { regexp: '^creative_mode = ', line: 'creative_mode = true' }
    - { regexp: '^port = ', line: 'port = {{ luanti_port }}' }
    - { regexp: '^default_game = ', line: 'default_game = {{ luanti_default_game }}' }

- name: Set mapgen engine to flat if enabled
  lineinfile:
    path: "{{ luanti_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^mg_name = ', line: 'mg_name = flat' }
  when: luanti_flat_world

- name: Create {{ luanti_world_dir }}
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ luanti_runas_user }}"
    group: "{{ luanti_runas_group }}"
    mode: 0755
  with_items:
    - "{{ luanti_world_dir }}"
