# 2019-07-08: legacy vars mongodb_install & mongodb_enabled are ignored at this time.

- name: Install 'mongodb' if not Debian 10+
  include_tasks: install.yml
  when: not ((is_debian and not is_raspbian) and (not is_debian_8) and (not is_debian_9))
