- name: Install MongoDB required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-server
    - mongodb
  when: internet_available
  tags:
    - download

- name: Create the data directory for MongoDB
  file:
    state: directory
    path: "{{ item.path }}"
    owner: mongodb
  with_items:
    - { path: '/var/run/mongodb' }
    - { path: "{{ mongodb_db_path }}" }
    - { path: '/var/log/mongodb' }

- name: Populate & position /etc/mongod.conf, /etc/systemd/system/mongodb.service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'mongodb.service.j2', dest: '/etc/systemd/system/mongodb.service' }
    - { src: 'mongod.conf.j2', dest: "{{ mongodb_conf }}" }

- name: Restart service if enabled
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: restarted
  with_items:
    - { name: mongodb }
  when: mongodb_enabled

- name: Stop service if not enabled
  service:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  with_items:
    - { name: mongodb }
  when: not mongodb_enabled

- name: Add 'mongodb' to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: mongodb
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: MongoDB
    - option: description
      value: '"MongoDB is an open-source document database that provides high performance, high availability, and automatic scaling."'
    - option: enabled
      value: "{{ mongodb_enabled }}"
