# The values here are defaults.
# To override them edit /etc/iiab/local_vars.yml

# Installation Variables
transmission_install: False
transmission_enabled: False

# Provision Transmission with default torrents
transmission_provision: True

transmission_KaLite-Version: 0.17
transmission_KaLite-Languages: English

transmission_download_dir: /library/transmission

#TODO Open this port to WAN.
#TODO Also open the default peer port 51413 and range 65535-49152
transmission_http_port: 9091
transmission_peer_port: 51413

transmission_url : "/transmission/"

transmission_username: Admin
transmission_password: changeme
