language: python
python: "3.8"
dist: focal

#addons:
#  apt:
#    packages:
#    - python-pip

install:
#  - scripts/ansible    # See #2105: fails to install latest Ansible (& ~4 Ansible Collections from collections.yml) due to Travis VM's disk layout/perms being different
#  - pip install ansible    # SLOW/OVERWEIGHT: installs Ansible 3.0.0+ with ~80 Ansible Collections
  - pip install ansible-base    # Install latest ansible-base 2.10.6+, similar to https://github.com/iiab/iiab/blob/master/scripts/ansible
  - ansible-galaxy collection install -r collections.yml    # Install ~4 Ansible Collections
  - "{ echo 'roles_path = ./roles/'; } >> ansible.cfg"    # Add correct roles_path to ansible.cfg, appending to https://github.com/iiab/iiab/blob/master/ansible.cfg
#  - "{ echo '[defaults]'; echo 'roles_path = ./roles/'; } >> ansible.cfg"    # Create ansible.cfg with correct roles_path and local_tmp
#  - cat ansible.cfg    # UNCOMMENT TO VERIFY!

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
