language: python
python: "3.8"
dist: focal
#addons:
#  apt:
#    packages:
#    - python-pip
install:
#  - scripts/ansible    # Fails to install latest Ansible (& ~4 Ansible Collections from collections.yml)
#  - pip install ansible    # SLOW/OVERWEIGHT: installs Ansible 3.0.0+ with ~80 Ansible Collections
  - pip install ansible-base    # Let's avoid all Ansible Collections for now (for Ansible syntax check!)
  - "{ echo 'roles_path = ./roles/'; } >> ansible.cfg"    # Add correct roles_path to ansible.cfg
#  - "{ echo '[defaults]'; echo 'roles_path = ./roles/'; } >> ansible.cfg"    # Create ansible.cfg with correct roles_path and local_tmp
#  - cat ansible.cfg    # UNCOMMENT TO VERIFY
script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
