language: python
python: "3.8"
dist: focal
#addons:
#  apt:
#    packages:
#    - python-pip
install:
  - scripts/ansible    # Install latest Ansible & ~4 Ansible Collections (collections.yml)
#  - pip install ansible
#  # Create ansible.cfg with correct roles_path and local_tmp
#  - "{ echo '[defaults]'; echo 'roles_path = ./roles/'; } >> ansible.cfg"
script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
