
name: Test
on: push
jobs:
  test_dispatch:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: depot/setup-action@v1
      - name: Build and Push with Depot
      - name: Call a different workflow
        env:
          DEPOT_SECRET_TOKEN: ${{ secrets.DEPOT_SECRET_TOKEN }}
        run: DEPOT_TOKEN="$DEPOT_SECRET_TOKEN" depot ci dispatch --repo Akatama/website --workflow build.yaml --ref depot-ci
