---
- hosts: all
  become: yes

  vars_files:
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - /etc/iiab/local_vars.yml

  roles:
    - { role: 0-init, tags: ['0-init'] }
    #- { role: 1-prep, tags: ['1-prep', 'platform', 'base'] }
    - { role: 1-prep, tags: ['1-prep'] }
    #- { role: openvpn, tags: ['openvpn'] }    # no longer nec, as 1-prep calls role openvpn (2018-09-19)
