# TEST ANSIBLE COMMANDS/MODULES IN SECONDS -- BY RUNNING:
# ansible-playbook -i ansible_hosts test.yml --connection=local

- hosts: all
  become: yes    # Optional privilege escalation

  #vars_files:
  #- roles/0-init/defaults/main.yml
  #- vars/default_vars.yml
  #- vars/{{ ansible_local.local_facts.os_ver }}.yml
  #- /etc/iiab/local_vars.yml
  #- /etc/iiab/iiab_state.yml

  #roles:
  #  - { role: 0-init }

  tasks:

  #- include_role:
  #    name: 0-init

  - debug:
      msg: "{{ 'changeme' | password_hash('sha512') }}"
      # msg: "{{ 'changeme' | password_hash('yescrypt') }}"    # crypt.crypt STILL doesn't support 'yescrypt' algorithm ?

  #- pause:

  - name: DOUBLE UP to escape single quotes... '"''"' e.g. iiab.ini Munin description
    debug:
      msg: '"''"'    # FAILS: '"\'"'

  - name: BACKSLASH to escape double quotes... "'\"'" e.g. cups/tasks/install.yml
    debug:
      msg: "'\"'"    # FAILS: "'""'"

  - name: a shows "VARIABLE IS NOT DEFINED!" -- whereas b (w/o whitespace) AND c (with space) AND d (with tab, STRICTLY DISALLOWED IN YAML BY ansible-core 2.11.6) showed null (without quotes!) -- whereas e (singlequotes) and f (doublequotes) show "" empty string
    set_fact:
      #a:
      b:
      c: # Space
      #d:	# Tab
      e: ''
      f: ""

  - debug:
      var: a
  - debug:
      var: b
  - debug:
      var: c
  - debug:
      var: d
  - debug:
      var: e
  - debug:
      var: f

  # TEST ANSIBLE COMMANDS/MODULES HERE!
