# TEST ANSIBLE COMMANDS/MODULES IN SECONDS -- BY RUNNING:
# ansible-playbook -i ansible_hosts test.yml --connection=local

- hosts: all
  become: yes    # Optional privilege escalation

  #vars_files:
  #- roles/0-init/defaults/main.yml
  #- vars/default_vars.yml
  #- vars/{{ ansible_local.local_facts.os_ver }}.yml
  #- /etc/iiab/local_vars.yml
  #- /etc/iiab/iiab_state.yml

  #roles:
  #  - { role: 0-init }

  tasks:

  #- include_role:
  #    name: 0-init

  - debug:
      msg: "{{ 'changeme' | password_hash('sha512') }}"

  #- pause:

  - name: DOUBLE UP to escape single quotes... '"''"' e.g. iiab.ini Munin description
    debug:
      msg: '"''"'    # FAILS: '"\'"'

  - name: BACKSLASH to escape double quotes... "'\"'" e.g. cups/tasks/install.yml
    debug:
      msg: "'\"'"    # FAILS: "'""'"

  # TEST ANSIBLE COMMANDS/MODULES HERE!
