# 2021-07-02 WARNING: Stage 4's roles/www_options/tasks/main.yml FORCES
# (the equivalent of) 'nginx_high_php_limits: True' if 'moodle_install: True'

# moodle_install: False
# moodle_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!


# 2023-04-25: Currently testing Moodle's master branch is mandatory if your
# OS PHP >= 8.3, see moodle/tasks/install.yml for detail!  OR, *IF* your
# OS PHP < 8.3, then {{ moodle_version }} will be attempted:
moodle_version: MOODLE_404_STABLE    # Moodle 4.4
#moodle_version: master              # e.g. to try Moodle's "weekly" 4.5dev pre-release *EVEN IF* OS PHP < 8.4
moodle_repo_url: https://github.com/moodle/moodle
#moodle_repo_url: git://git.moodle.org/moodle.git    # 2020-10-16: VERY Slow!

moodle_base: "{{ iiab_base }}/moodle"       # /opt/iiab
moodle_data: "{{ content_base }}/moodle"    # /library

moodle_db_name: moodle
moodle_db_user: Admin
moodle_db_pass: changeme
