# 2021-07-02 WARNING: Stage 4's roles/www_options/tasks/main.yml FORCES
# (the equivalent of) 'nginx_high_php_limits: True' if 'moodle_install: True'

# moodle_install: False
# moodle_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!


# 2022-09-27: Currently testing Moodle's master branch is mandatory if your
# OS PHP >= 8.1 -- see moodle/tasks/install.yml for detail!
# (Any moodle_version setting below applies IF-AND-ONLY-IF your OS PHP < 8.1)
#moodle_version: master              # Try Moodle's "weekly" 4.1dev pre-release, even if OS PHP < 8.1
moodle_version: MOODLE_400_STABLE    # Use Moodle 4.0
moodle_repo_url: https://github.com/moodle/moodle
#moodle_repo_url: git://git.moodle.org/moodle.git    # 2020-10-16: VERY Slow!

moodle_base: "{{ iiab_base }}/moodle"    # /opt/iiab
moodle_data: "{{ content_base }}/moodle"    # /library

moodle_db_name: moodle
moodle_db_user: Admin
moodle_db_pass: changeme
