# 2021-08-04: Stanza below commonly causes systemd error "Asterisk is already
# running.  /etc/init.d/asterisk will exit now" (initial installs especially?)
#
# But without this stanza, 'systemctl restart freepbx' all alone during initial
# install ALSO fails to start Asterisk reliably, on Ubuntu 20.04 & Debian 11 :/
#
# Yes /etc/systemd/system/freepbx.service is supposed to run 'fwconsole stop'
# then 'fwconsole start' reliably, as many web posts recommend, But No Dice!
#
# Do we need something like 'RestartSec=3' in freepbx.service ??
#
#- name: Enable & (Re)start 'asterisk' systemd service (if pbx_enabled)
#  systemd:
#    daemon_reload: yes
#    name: asterisk
#    enabled: yes
#    state: restarted
#  when: pbx_enabled

#- name: Disable & Stop 'asterisk' systemd service (if not pbx_enabled)
#  systemd:
#    daemon_reload: yes
#    name: asterisk
#    enabled: no
#    state: stopped
#  when: not pbx_enabled


- name: Enable & (Re)start 'freepbx' systemd service (if pbx_enabled)
  systemd:
    name: freepbx
    enabled: yes
    state: restarted
  when: pbx_enabled

- name: Disable & Stop 'freepbx' systemd service (if not pbx_enabled)
  systemd:
    name: freepbx
    enabled: no
    state: stopped
  when: not pbx_enabled


- name: Enable http://box:{{ pbx_http_port }}/freepbx via Apache, if pbx_enabled    # http://box:83/freepbx
  command: a2ensite freepbx.conf
  when: pbx_enabled

- name: Disable http://box:{{ pbx_http_port }}/freepbx via Apache, if not pbx_enabled
  command: a2dissite freepbx.conf
  when: not pbx_enabled

- name: Restart Apache service ({{ apache_service }})
  systemd:
    name: "{{ apache_service }}"    # httpd or apache2
    state: restarted
