- name: Enable & (Re)start 'asterisk' systemd service (if pbx_enabled)
  systemd:
    daemon_reload: yes
    name: asterisk
    enabled: yes
    state: restarted
  when: pbx_enabled

- name: Disable & Stop 'asterisk' systemd service (if not pbx_enabled)
  systemd:
    daemon_reload: yes
    name: asterisk
    enabled: no
    state: stopped
  when: not pbx_enabled


- name: Enable & (Re)start 'freepbx' systemd service (if pbx_enabled)
  systemd:
    name: freepbx
    enabled: yes
    state: restarted
  when: pbx_enabled

- name: Disable & Stop 'freepbx' systemd service (if not pbx_enabled)
  systemd:
    name: freepbx
    enabled: no
    state: stopped
  when: not pbx_enabled


- name: Enable http://box:{{ pbx_http_port }}/freepbx via Apache, if pbx_enabled    # http://box:83/freepbx
  command: a2ensite freepbx.conf
  when: pbx_enabled

- name: Disable http://box:{{ pbx_http_port }}/freepbx via Apache, if not pbx_enabled
  command: a2dissite freepbx.conf
  when: not pbx_enabled

- name: Restart Apache service ({{ apache_service }})
  systemd:
    name: "{{ apache_service }}"    # httpd or apache2
    state: restarted
