- name: FreePBX - Install dependencies
  package:
    name:
    - wget
    - git 
    - unixodbc # for asterisk cdr
    - sudo # required by freepbx install script
    - net-tools # fwconsole requirement
    - cron # required by freepbx ucp package
    - sox # required for CDR web-playback
    - php 
    - php-pear
    - php-cgi
    - php-common
    - php-curl
    - php-mbstring
    - php-gd
    - php-mysql
    - php-gettext
    - php-bcmath
    - php-zip
    - php-xml
    - php-imap
    - php-json
    - php-snmp 
    - php-fpm
    - libapache2-mod-php
    - python-mysqldb # https://github.com/Yannik/ansible-role-freepbx/blob/master/tasks/freepbx.yml#L33
    state: latest
