- name: FreePBX - Install dependencies
  package:
    name:
      - wget
      - git 
      - unixodbc     # for Asterisk CDR (Call Detail Records)
      - sudo         # required by FreePBX install script
      - net-tools    # required by FWConsole (command-line utility, that controls FreePBX)
      - cron         # required by FreePBX UCP package (User Control Panel)
      - sox          # required for CDR web-playback
      #- php{{ php_version }}    # Drags in phpX.Y-cgi (already below!)
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-cgi
      #- php{{ php_version }}-common    # Auto-installed as a dependency
      - php{{ php_version }}-curl
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-imap
      #- php{{ php_version }}-json    # See stanza just below
      #- php{{ php_version }}-gettext
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php-pear
      - php{{ php_version }}-snmp 
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - libapache2-mod-php
      #- python-mysqldb        # https://github.com/Yannik/ansible-role-freepbx/blob/master/tasks/freepbx.yml#L33
      - libapache2-mpm-itk    # To serve FreePBX through a VirtualHost as asterisk user
    state: latest

# For PHP >= 8.0: phpX.Y-json is baked into PHP itself.
# For PHP <  8.0: Auto-installed by phpX.Y-fpm AND phpX.Y-cli in roles/3-base-server, as confirmed by: apt rdepends phpX.Y-json
#
#- name: Install php{{ php_version }}-json if PHP < 8.0
#  package:
#    name: php{{ php_version }}-json
#    state: present
#  when: php_version is version('8.0', '<')
