- name: FreePBX - Install dependencies
  include: freepbx_dependencies.yml

- name: FreePBX - Download software to /opt/iiab/downloads
  get_url:
    url: "{{ freepbx_url }}/{{ freepbx_src_file }}"
    dest: "{{ downloads_dir }}/{{ freepbx_src_file }}"
    timeout: "{{ download_timeout }}"
  when: internet_available

- name: FreePBX - Check for /opt/iiab/downloads/{{ freepbx_src_file }}
  stat:
    path: "{{ downloads_dir }}/{{ freepbx_src_file }}"
  register: freepbx_src

- name: FreePBX - FAIL (force Ansible to exit) IF /opt/iiab/downloads/{{ freepbx_src_file }} doesn't exist
  fail:
    msg: "{ downloads_dir }}/{{ freepbx_src_file }} is REQUIRED in order to install."
  when: not freepbx_src.stat.exists

- name: FreePBX - Create install source directory
  file: 
    path: "{{ freepbx_src_dir }}"
    state: directory

- name: FreePBX - Extract source
  unarchive: 
    src: "{{ downloads_dir }}/{{ freepbx_src_file }}"
    dest: "{{ freepbx_src_dir }}"
    owner: root
    group: root
    extra_opts: [--strip-components=1]

- name: FreePBX - Disable & Stop asterisk service
  systemd:
    daemon_reload: yes
    name: asterisk
    enabled: no
    state: stopped

- name: Install freepbx (just ran once)
  command: "{{ item }}"
  args:
    chdir: "{{ freepbx_src_dir }}"
    creates: /var/www/html/freepbx
  with_items:
    - ./start_asterisk start
    - ./install -n --webroot /var/www/html/freepbx --dbuser root --dbpass {{ mysql_root_password }} 
  register: freepbx_installation

- name: Create /etc/odbc.ini
  template:
    src: odbc.ini.j2
    dest: /etc/odbc.ini
    owner: root
    group: root
    mode: 0644
