- name: FreePBX - Install dependencies
  include: freepbx_dependencies.yml

- name: FreePBX - Download software to /opt/iiab/downloads
  get_url:
    url: "{{ freepbx_url }}/{{ freepbx_src_file }}"
    dest: "{{ downloads_dir }}/{{ freepbx_src_file }}"
    timeout: "{{ download_timeout }}"
  when: internet_available

- name: FreePBX - Check for {{ downloads_dir }}/{{ freepbx_src_file }}
  stat:
    path: "{{ downloads_dir }}/{{ freepbx_src_file }}"
  register: freepbx_src

- name: FreePBX - FAIL (force Ansible to exit) IF {{ downloads_dir }}/{{ freepbx_src_file }} doesn't exist
  fail:
    msg: "{ downloads_dir }}/{{ freepbx_src_file }} is REQUIRED in order to install."
  when: not freepbx_src.stat.exists

- name: FreePBX - Create install source directory
  file: 
    path: "{{ freepbx_src_dir }}"
    state: directory

- name: FreePBX - Extract source
  unarchive: 
    src: "{{ downloads_dir }}/{{ freepbx_src_file }}"
    dest: "{{ freepbx_src_dir }}"
    owner: root
    group: root
    extra_opts: [--strip-components=1]

- name: FreePBX - Disable & Stop asterisk service
  systemd:
    daemon_reload: yes
    name: asterisk
    enabled: no
    state: stopped

- name: FreePBX - Install (just run once)
  command: "{{ item }}"
  args:
    chdir: "{{ freepbx_src_dir }}"
    creates: "{{ freepbx_install_dir }}"
  with_items:
    - ./start_asterisk start
    - ./install -n --webroot {{ freepbx_install_dir }} --dbuser root --dbpass {{ mysql_root_password }} 
  register: freepbx_installation

- name: FreePBX - Create /etc/odbc.ini
  template:
    src: odbc.ini.j2
    dest: /etc/odbc.ini
    owner: root
    group: root
    mode: 0644

- name: FreePBX - Copy freepbx.conf
  template:
    src: freepbx.conf.j2
    dest: /etc/apache2/sites-available/freepbx.conf
    owner: www-data
    group: www-data
    mode: 0644

- name: FreePBX - Link freepbx.conf apache file to sites-enabled
  file: 
    src: /etc/apache2/sites-available/freepbx.conf
    dest: /etc/apache2/sites-enabled/freepbx.conf
    state: link
  when: pbx_enabled

- name: FreePBX - Unlink freepbx.conf apachefile from sites-enabled
  file: 
    path: /etc/apache2/sites-enabled/freepbx.conf
    state: absent
  when: (not pbx_enabled)

- name: FreePBX - Copy systemd unit file
  template:
    src: freepbx.service.j2
    dest: /etc/systemd/system/freepbx.service
    mode: 755

- name: FreePBX - Enable and Start freepbx service
  systemd:
    daemon_reload: yes
    name: freepbx
    enabled: yes
    state: started
  when: pbx_enabled

- name: FreePBX - Disable & Stop freepbx service
  systemd:
    daemon_reload: yes
    name: freepbx
    enabled: no
    state: stopped
  when: (not pbx_enabled)
