# (PRE-)release version number, for {{ iiab_env_file }} = /etc/iiab/iiab.env
# iiab_base_ver: 7.1
# iiab_revision: 0
# ABOVE MOVED TO /opt/iiab/iiab/vars/default_vars.yml

# These entries should never be changed in this file.
# These are defaults for boolean routines.
first_run: False
rpi_model: none
xo_model: none
gw_active: False
internet_available: False
discovered_wan_iface: none

# Old defs
gui_port: 80
is_F18: False

# Set default 1-prep discovered hardware
rtc_id: none
NUC6_firmware_needed: False

# Used in 2-common/tasks/xo.yml
wifi_id: none

# 2021-07-30: roles/network/tasks/squid.yml#L16 to stop Squid
# ("when: not installing") is the only non-Fedora use of this var.
# Earlier, this var HAD also been used in 2-common and 3-base-server.
installing: False

# Network
no_net_restart: False
no_NM_reload: False
