# https://remote.it can help you remotely maintain an IIAB.

# remoteit_install: True
# remoteit_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

remoteit_version: 4.13.5

# See https://docs.remote.it/device-package/installation to refine URL below:
device_suffixes:
  armv6: armhf.rpi
  armv6l: armhf.rpi
  armv7: armhf.rpi
  armv7l: armhf.rpi
  armv8: arm64.rpi
  aarch64: arm64
  x86_64: amd64
remoteit_device_suffix: "{{ device_suffixes[ansible_architecture] | default('unknown') }}"
remoteit_deb: remoteit-{{ remoteit_version }}.{{ remoteit_device_suffix }}.deb
remoteit_device_url: https://downloads.remote.it/remoteit/v{{ remoteit_version }}/{{ remoteit_deb }}
# Example...         https://downloads.remote.it/remoteit/v4.13.5/remoteit-4.13.5.armhf.rpi.deb

# See https://docs.remote.it/cli/overview to refine URL below:
cli_suffixes:
  armv6: armv6
  armv6l: armv6
  armv7: armv7
  armv7l: armv7
  armv8: arm64
  aarch64: arm64
  x86_64: amd64
remoteit_cli_suffix: "{{ cli_suffixes[ansible_architecture] | default('unknown') }}"
remoteit_cli_url: https://downloads.remote.it/cli/latest/remoteit_linux_{{ remoteit_cli_suffix }}
# Example...      https://downloads.remote.it/cli/latest/remoteit_linux_armv7
