# https://remote.it can help you remotely maintain an IIAB.

# remoteit_install: True
# remoteit_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

# See https://docs.remote.it/cli/overview to refine either value below:
remoteit_cli_url: https://downloads.remote.it/cli/latest/remoteit_linux_armv7
remoteit_device_url: https://downloads.remote.it/remoteit/v4.13.5/remoteit-4.13.5.armhf.rpi.deb
