# These are set in github.com/iiab/iiab/blob/master/vars/default_vars.yml
# They may be overridden in local_vars

# minetest_install: False
# minetest_enabled: False
# minetest_port: 30000
# minetest_server_admin: Admin

# minetest_default_game: only carbone-ng and minetest are supported
minetest_default_game: carbone-ng
minetest_flat_world: False

# These should not be touched unless minetest packages change

minetest_config_file: /etc/minetest/minetest.conf
minetest_world_dir: /library/games/minetest/worlds/world
