# A full-featured online radio station suite.
# Works on Ubuntu 18.04, Debian 9, 10. Uses docker

# azuracast_install: False
# azuracast_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

azuracast_http_port: 8080
azuracast_https_port: 8443

docker_sh_url: https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh
docker_container_dir: /library/docker
azuracast_host_dir: /opt/azuracast
