# SEE "emergency" REINSTALL INSTRUCTIONS IN roles/wordpress/tasks/install.yml

- name: Provision MySQL DB for WordPress, if 'wordpress_installed' is not defined in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: setup.yml
  when: wordpress_installed is undefined    # and not installing

- name: Install WordPress if 'wordpress_installed' is not defined in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: wordpress_installed is undefined

- name: Enable or Disable WordPress
  include_tasks: enable-or-disable.yml

- name: Add 'wordpress' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: wordpress
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: WordPress
    - option: description
      value: '"WordPress is a blog and web site management application."'
    - option: wordpress_src
      value: "{{ wordpress_src }}"
    - option: wp_abs_path
      value: "{{ wp_abs_path }}"
    - option: wp_db_name
      value: "{{ wp_db_name }}"
    - option: wp_db_user
      value: "{{ wp_db_user }}"
    - option: wp_url
      value: "{{ wp_url }}"
    - option: wp_full_url
      value: "{{ wp_full_url }}"
    - option: wordpress_enabled
      value: "{{ wordpress_enabled }}"
