# This is rpi only

- name: "Install rpi bluetooth packages"
  package:
    name:
      - bluetooth
      - bluez
      - bluez-tools
    state: present

- name: Create bluetooth services
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'bt-agent.service.j2', dest: '/etc/systemd/system/bt-agent.service' }
    - { src: 'bt-pan.service.j2', dest: '/etc/systemd/system/bt-pan.service' }
    - { src: 'bt-term.service.j2', dest: '/etc/systemd/system/bt-term.service' }
    - { src: 'iiab-bt-pan-on.j2', dest: '/usr/bin/iiab-bt-pan-on' }
    - { src: 'iiab-bt-pan-off.j2', dest: '/usr/bin/iiab-bt-pan-off' }
    - { src: 'iiab-bt-term-on.j2', dest: '/usr/bin/iiab-bt-term-on' }
    - { src: 'iiab-bt-term-off.j2', dest: '/usr/bin/iiab-bt-term-off' }

# enable or disable bt-agent
- name: Enable & Restart 'bt-agent' service
  systemd:
    daemon_reload: yes
    name: bt-agent
    enabled: yes
    state: restarted
  when: bluetooth_enabled or bluetooth_term_enabled

- name: Disable 'bt-agent' service
  systemd:
    daemon_reload: yes
    name: bt-agent
    enabled: no
    state: stopped
  when: not bluetooth_enabled and not bluetooth_term_enabled

# enable or disable bt-pan
- name: Enable & Restart 'bt-pan' service
  systemd:
    daemon_reload: yes
    name: bt-pan
    enabled: yes
    state: restarted
  when: bluetooth_enabled | bool

- name: Disable 'bt-pan' service
  systemd:
    daemon_reload: yes
    name: bt-pan
    enabled: no
    state: stopped
  when: not bluetooth_enabled | bool

# enable or disable bt-term
- name: Enable & Restart 'bt-term' service
  systemd:
    daemon_reload: yes
    name: bt-term
    enabled: yes
    state: restarted
  when: bluetooth_term_enabled | bool

- name: Disable 'bt-term' service
  systemd:
    daemon_reload: yes
    name: bt-term
    enabled: no
    state: stopped
  when: not bluetooth_term_enabled | bool

- name: Add 'bluetooth' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: bluetooth
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: Bluetooth
    - option: description
      value: '"Bluetooth services for pan and terminal."'
    - option: bluetooth_enabled
      value: "{{ bluetooth_enabled }}"
    - option: bluetooth_term_enabled
      value: "{{ bluetooth_term_enabled }}"
