# XO Services

- name: ...IS BEGINNING =====================================
  command: echo

- name: ACTIVITY-SERVER
  include_role:
    name: activity-server
  when: activity_server_install
  tags: olpc, activity-server

- name: EJABBERD_XS
  include_role:
    name: ejabberd_xs
  when: ejabberd_xs_install
  tags: olpc, ejabberd-xs

- name: IDMGR
  include_role:
    name: idmgr
  when: idmgr_install
  tags: olpc, idmgr

- name: ...HAS COMPLETED ====================================
  command: echo
