# XO Services

- name: ...IS BEGINNING =====================================
  command: echo

# UNMAINTAINED
- name: ACTIVITY-SERVER
  include_role:
    name: activity-server
  when: activity_server_install | bool

# UNMAINTAINED
- name: EJABBERD_XS
  include_role:
    name: ejabberd_xs
  when: ejabberd_xs_install | bool

# UNMAINTAINED
- name: IDMGR
  include_role:
    name: idmgr
  when: idmgr_install | bool

- name: Recording STAGE 5 HAS COMPLETED =====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=5'
