# XO Services

- name: ...IS BEGINNING =====================================
  command: echo

- name: ACTIVITY-SERVER
  include_role:
    name: activity-server
  when: activity_server_install | bool
  #tags: olpc, activity-server

- name: EJABBERD_XS
  include_role:
    name: ejabberd_xs
  when: ejabberd_xs_install | bool
  #tags: olpc, ejabberd-xs

- name: IDMGR
  include_role:
    name: idmgr
  when: idmgr_install | bool
  #tags: olpc, idmgr

- name: Recording STAGE 5 HAS COMPLETED =====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=5'
