# Server Options

- name: ...IS BEGINNING ============================================]
  command: echo

- name: HOMEPAGE
  include_role:
    name: homepage
  tags: base, homepage

- name: SSHD
  include_role:
    name: sshd
  tags: base, sshd

- name: NETWORK
  include_role:
    name: network
  tags: base, network

# the above 3 have no "when: XXXXX_install" flag -- whereas the 5 below do

- name: AUTHSERVER
  include_role:
    name: authserver
  when: authserver_install
  tags: authserver

- name: OPENVPN
  include_role:
    name: openvpn
  when: openvpn_install
  tags: openvpn

- name: SAMBA
  include_role:
    name: samba
  when: samba_install
  tags: samba

- name: USB-LIB
  include_role:
    name: usb-lib
  when: usb_lib_install
  tags: usb-lib

- name: CUPS
  include_role:
    name: cups
  when: cups_install
  tags: cups

# this script can be sourced to get iiab location
- name: Create iiab.env file
  template: src=roles/1-prep/templates/iiab.env.j2
            dest=/etc/iiab/iiab.env
            owner=root
            group=root
            mode=0644

- name: put a python interface to iiab.env
  template: src=roles/1-prep/templates/iiab_env.py.j2
            dest=/etc/iiab/iiab_env.py

- name: generate the offline documents
  command: /usr/bin/iiab-refresh-wiki-docs
  when: not nodocs

- name: Stop postgresql service
  command: "/etc/init.d/postgresql stop"
  ignore_errors: True
  when: postgresql_install and is_debuntu

- name: Start postgresql service
  service: name=postgresql-iiab
           state=restarted
           enabled=yes
  when: postgresql_enabled

- name: Stop authserver service
  service: name=xs-authserver
           state=stopped
           enabled=no
  when: not authserver_enabled and authserver_install

- name: Start xs-authserver service
  service: name=xs-authserver
           state=restarted
  when: authserver_enabled

- name: ...WAS COMPLETED ===========================================]
  command: echo
