# Server Options

- name: ...IS BEGINNING ==================================
  file:
    path: "{{ iiab_state_file }}"
    state: touch

- name: Install named / BIND
  include_tasks: roles/network/tasks/named.yml
  when: named_install | bool

- name: Installing dhcpd
  include_tasks: roles/network/tasks/dhcpd.yml
  when: dhcpd_install | bool

- name: Install Squid (and DansGuardian if dansguardian_install)
  include_tasks: roles/network/tasks/squid.yml
  when: squid_install | bool

- name: Install Bluetooth - only on Raspberry Pi
  include_role:
    name: bluetooth
  when: is_rpi and bluetooth_install

- name: USB_LIB
  include_role:
    name: usb_lib
  when: usb_lib_install | bool

# This is in Stage 4-SERVER-OPTIONS (rather than 3-BASE-SERVER) because var
# iiab_home_url changes, and may need to be re-run in the field/offline/etc.
- name: HOMEPAGE under Apache
  include_role:
    name: homepage
  when: not nginx_enabled

- name: CUPS
  include_role:
    name: cups
  when: cups_install | bool

- name: SAMBA
  include_role:
    name: samba
  when: samba_install | bool

# DOES THE FLAG BELOW (apache_allow_sudo) WORK WITH NGINX TOO ?

- name: Give {{ apache_user }} (per variable apache_user) permission to poweroff, installing /etc/sudoers.d/020_apache_poweroff from template
  template:
    src: 020_apache_poweroff.j2
    dest: /etc/sudoers.d/020_apache_poweroff
    mode: '0755'
  when: apache_allow_sudo | bool

- name: Remove {{ apache_user }} (per variable apache_user) permission to poweroff, removing /etc/sudoers.d/020_apache_poweroff
  file:
    path: /etc/sudoers.d/020_apache_poweroff
    state: absent
  when: not apache_allow_sudo

- name: Run /usr/bin/iiab-refresh-wiki-docs (scraper script) to create http://box/info offline documentation.  (This script was installed at the beginning of Stage 3 = roles/3-base-server/tasks/main.yml, which ran Apache playbook = roles/httpd/tasks/main.yml)
  command: /usr/bin/iiab-refresh-wiki-docs
  when: internet_available and not nodocs

- name: Recording STAGE 4 HAS COMPLETED ==================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=4'
