# 1. INSTALL THE LATEST CALIBRE (calibre-server etc) ON ALL OS'S

# RUNS IF /usr/bin/calibre-uninstall DOES NOT ALEADY EXIST
- name: Install Calibre via calibre-installer.py (OS's other than Raspbian)
  include_tasks: py-installer.yml
  when: not is_rpi
  #when: not calibre_db.stat.exists and (is_redhat or is_ubuntu)

- name: Install Calibre via .debs (Raspbian)
  include_tasks: debs.yml
  when: is_rpi

# 2. CREATE DATABASE WITH A SAMPLE BOOK (REQUIRED AS OF CALIBRE 3.x)

- name: Check if /library/calibre/metadata.db exists
  stat:
    path: "{{ calibre_dbpath }}/metadata.db"
  register: calibre_db

- name: Create database (required since Calibre 3.x) with a sample book
  include_tasks: create-db.yml
  when: not calibre_db.stat.exists

# 3. WRAP UP CALIBRE INSTALLATION

- name: Create calibre-serve.service and calibre.conf
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'calibre-serve.service.j2', dest: '/etc/systemd/system/calibre-serve.service', mode: '0644'}
    - { src: 'calibre.conf', dest: '/etc/{{ apache_config_dir }}', mode: '0644'}
  when: calibre_enabled

# http://box:8080 & http://box:8080/mobile WORK BUT OTHER URL'S LIKE http://box/books ARE A MESS (BOOKS RARELY DISPLAY)
- name: Create calibre.conf link for UNTESTED http://box/books etc (debuntu)
  file:
    src: /etc/apache2/sites-available/calibre.conf
    dest: /etc/apache2/sites-enabled/calibre.conf
    state: link
  when: calibre_enabled and is_debuntu

- name: Remove calibre.conf link if disabled (debuntu)
  file:
    dest: /etc/apache2/sites-enabled/calibre.conf
    state: absent
  when: not calibre_enabled and is_debuntu

- name: Enable Calibre service -- runs calibre-server by Kovid Goyal
  service:
    name: calibre-serve
    enabled: yes
    state: started
  when: calibre_enabled
  #async: 900
  #poll: 5

#- name: Disable Calibre service -- stops calibre-server by Kovid Goyal
#  service: name=calibre-serve
#           enabled=no
#           state=stopped
#  when: not calibre_enabled

- name: Add 'calibre-serve' to service list at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: calibre
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: description
      value: '"Calibre is an extremely popular personal library system for e-books."'
    - option: url
      value: "{{ calibre_src_url }}"
    - option: database
      value: "{{ calibre_dbpath }}"
    - option: port
      value: "{{ calibre_port }}"
    - option: enabled
      value: "{{ calibre_enabled }}"
