- name: Check for Minetest world file ({{ minetest_world_dir }}/world.mt)
  stat:
    path: "{{ minetest_world_dir }}/world.mt"
  register: minetest_world

- name: mkdir /library/games
  file:
    state: directory
    path: /library/games
    # owner: root
    # group: root
    # mode: '0755'

- include_tasks: minetest_install.yml
  when: not minetest_world.stat.exists

# Install games
#- include_tasks: minetest_install_games.yml
#  with_items:
#    - name: carbone-ng
#      url: https://github.com/Calinou/carbone-ng

# Install mods
- include_tasks: minetest_install_mods.yml
  with_items:
    - name: moreblocks
      url: https://github.com/minetest-mods/moreblocks/archive/master.zip
    - name: moreores
      url: https://github.com/Calinou/moreores/archive/master.zip
    - name: basic_materials
      url: https://gitlab.com/VanessaE/basic_materials/-/archive/master/basic_materials-master.zip
    - name: mesecons
      url: https://github.com/minetest-mods/mesecons/archive/master.zip
    - name: digilines
      url: https://github.com/minetest-mods/digilines/archive/master.zip
    - name: pipeworks
      url: https://github.com/minetest-mods/pipeworks/archive/master.zip
    - name: Minetest-WorldEdit
      url: https://github.com/Uberi/Minetest-WorldEdit/archive/master.zip
  when: minetest_default_game == "minetest"

# RECORD Minetest AS INSTALLED

- name: "Set 'minetest_installed: True'"
  set_fact:
    minetest_installed: True

- name: "Add 'minetest_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^minetest_installed'
    line: 'minetest_installed: True'
