- name: Check for Minetest world file ({{ minetest_world_dir }}/world.mt)
  stat:
    path: "{{ minetest_world_dir }}/world.mt"
  register: minetest_world

- name: mkdir /library/games
  file:
    state: directory
    path: /library/games
    # owner: root
    # group: root
    # mode: '0755'

- include_tasks: minetest_install.yml
  when: not minetest_world.stat.exists

# Install games
#- include_tasks: minetest_install_games.yml
#  with_items:
#    - name: carbone-ng
#      url: https://github.com/Calinou/carbone-ng

# Install mods
- include_tasks: minetest_install_mods.yml
  with_items:
    - name: basic_materials
      url: https://content.minetest.net/packages/VanessaE/basic_materials/releases/14936/download/
    - name: mesecons
      url: https://content.minetest.net/packages/Jeija/mesecons/releases/14247/download/
    - name: digilines
      url: https://content.minetest.net/packages/Jeija/digilines/releases/13248/download/
    - name: pipeworks
      url: https://content.minetest.net/packages/VanessaE/pipeworks/releases/7488/download/
    - name: Minetest-WorldEdit
      url: https://content.minetest.net/packages/sfan5/worldedit/releases/13367/download/
  when: minetest_default_game == "minetest"

# RECORD Minetest AS INSTALLED

- name: "Set 'minetest_installed: True'"
  set_fact:
    minetest_installed: True

- name: "Add 'minetest_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^minetest_installed'
    line: 'minetest_installed: True'
