# For rpi installs

- name: Set some facts
  set_fact:
    rpi_src_url: http://www.nathansalapat.com/downloads/0.4.17.1.tar.gz
    rpi_src: minetest-0.4.17.1.tar.gz

- name: Install packages for minetest
  package:
          name: "{{ item }}"
          state: present
  with_items:
    - libhiredis-dev

#- name: Minetest already installed - terminate play
#  meta: end_play
#  when: minetest_world.stat.exists

- name: Download minetest for rpi
  get_url:
    url: "{{ rpi_src_url }}"
    dest: "{{ downloads_dir }}/{{ rpi_src }}"
    timeout: "{{ download_timeout }}"

- name: Create /etc/minetest and /library/games directories
  file:
        path: "{{ item }}"
        mode: 0755
        owner: root
        group: root
        state: directory
  with_items:
    - /etc/minetest
    - /library/games

- name: Create /var/log/minetest directory
  file:
        path: "{{ item }}"
        mode: 0755
        owner: "{{ minetest_runas_user }}"
        group: "{{ minetest_runas_group }}"
        state: directory
  with_items:
    - /var/log/minetest

- name: Extract minetest into /library/games
  unarchive:
    src: "{{ downloads_dir }}/{{ rpi_src }}"
    dest: /library/games
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"

- name: Create symbolic link
  file:
    src: /library/games/0.4.17.1
    dest: /library/games/minetest
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"
    state: link

- name: Create minetest-server service and minetest.conf file
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - { src: 'minetest.conf.j2', dest: '/etc/minetest/minetest.conf', mode: '0644'}
  - { src: 'minetest-serve.service.j2', dest: '/etc/systemd/system/minetest-serve.service', mode: '0644'}
