# For rpi installs

- name: Install 'libhiredis-dev' package for Minetest
  package:
    name: libhiredis-dev
    state: present

- name: Download Minetest {{ rpi_src_url }} for RPi
  get_url:
    url: "{{ rpi_src_url }}"
    dest: "{{ downloads_dir }}/{{ rpi_src }}"
    timeout: "{{ download_timeout }}"

- name: Extract {{ downloads_dir }}/{{ rpi_src }} into /library/games
  unarchive:
    src: "{{ downloads_dir }}/{{ rpi_src }}"
    dest: /library/games
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"

- name: Create symbolic link /library/games/minetest
  file:
    state: link
    src: /library/games/0.4.17.1
    dest: /library/games/minetest
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"
