- name: Symlink /etc/apache2/sites-enabled/dokuwiki.conf to /etc/apache2/sites-available/dokuwiki.conf if dokuwiki_enabled (debuntu)
  file:
    src: /etc/apache2/sites-available/dokuwiki.conf
    path: /etc/apache2/sites-enabled/dokuwiki.conf
    state: link
  when: dokuwiki_enabled and is_debuntu

- name: Remove symlink /etc/apache2/sites-enabled/dokuwiki.conf if not dokuwiki_enabled (debuntu)
  file:
    path: /etc/apache2/sites-enabled/dokuwiki.conf
    state: absent
  when: not dokuwiki_enabled and is_debuntu

- name: Install {{ nginx_config_dir }}/dokuwiki-nginx.conf SHIM from template
  template:
    src: dokuwiki-nginx.conf
    dest: "{{ nginx_config_dir }}/dokuwiki-nginx.conf"
  when: dokuwiki_enabled and nginx_enabled

- name: Restart Apache ({{ apache_service }}) to enable/disable DokuWiki's http://box/wiki
  systemd:
    name: "{{ apache_service }}"
    daemon_reload: yes
    state: restarted
  when: apache_enabled

- name: Restart nginx to enable/disable DokuWiki's http://box/wiki
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted
  when: nginx_enabled

- name: Add 'dokuwiki' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: dokuwiki
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: DokuWiki
    - option: description
      value: '"DokuWiki is a simple to use and highly versatile Open Source wiki software that does not require a database."'
    - option: installed
      value: "{{ dokuwiki_install }}"
    - option: enabled
      value: "{{ dokuwiki_enabled }}"

