# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "nextcloud_install is sameas true" (boolean not string etc)
  assert:
    that: nextcloud_install is sameas true
    fail_msg: "PLEASE SET 'nextcloud_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "nextcloud_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: nextcloud_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'nextcloud_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


#- name: Does {{ nextcloud_prefix }}//nextcloud/version.php exist?    # /opt
#  stat:
#    path: "{{ nextcloud_prefix }}/nextcloud/version.php"
#  register: nextcloud_page

- name: Install Nextcloud if 'nextcloud_installed' is not defined in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: nextcloud_installed is undefined     # or not nextcloud_page.stat.exists


- name: Enable/Disable/Restart Apache if primary
  include_tasks: apache.yml
  when: not nginx_enabled

- name: Enable/Disable/Restart NGINX if primary
  include_tasks: nginx.yml
  when: nginx_enabled | bool


- name: Add 'nextcloud' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: Nextcloud
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Nextcloud
    - option: description
      value: '"Nextcloud is a local server-based facility for sharing files, photos, contacts, calendars, etc."'
    - option: path
      value: "{{ nextcloud_prefix }}/nextcloud"
    - option: nextcloud_orig_src_file
      value: "{{ nextcloud_orig_src_file }}"
    - option: nextcloud_src_file
      value: "{{ nextcloud_src_file }}"
    - option: nextcloud_enabled
      value: "{{ nextcloud_enabled }}"
