# Educational Apps

- name: ...IS BEGINNING ========================================
  command: echo

- name: KALITE
  include_role:
    name: kalite
  when: kalite_install | bool
  #tags: kalite

- name: KOLIBRI
  include_role:
    name: kolibri
  when: kolibri_install | bool
  #tags: kolibri

- name: KIWIX
  include_role:
    name: kiwix
  when: kiwix_install | bool
  #tags: kiwix

- name: MOODLE
  include_role:
    name: moodle
  when: moodle_install | bool
  #tags: olpc, moodle

- name: OSM-VECTOR-MAPS
  include_role:
    name: osm-vector-maps
  when: osm_vector_maps_install | bool
  #tags: osm, maps

# UNMAINTAINED
- name: OSM
  include_role:
    name: osm
  when: osm_install is defined and osm_install
  #tags: osm, maps

# UNMAINTAINED
- name: PATHAGAR
  include_role:
    name: pathagar
  when: pathagar_install is defined and pathagar_install
  #tags: pathagar

- name: SUGARIZER
  include_role:
    name: sugarizer
  when: sugarizer_install | bool
  #tags: sugarizer

- name: Recording STAGE 7 HAS COMPLETED ========================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=7'
