- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Install /etc/dnsmasq.d/dnsmasq-iiab, allowing systemd-resolved AND dnsmasq to work (#1306) and custom unit file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
   - { src: 'roles/network/templates/network/dnsmasq.service.u18', dest: '/etc/systemd/system/iiab-dnsmasq.service', mode: '0644' }
   - { src: 'roles/network/templates/network/dnsmasq-iiab', dest: '/etc/dnsmasq.d/dnsmasq-iiab', mode: '644' }

- name: Copy script to restart dnsmasq whenever br0 comes up
  template: 
    src: "roles/network/templates/network/dnsmasq.sh.j2"
    dest: "/etc/networkd-dispatcher/routable.d/dnsmasq.sh"
    mode: "0755"
    owner: root
    group: root

- name: Don't use stock dnsmasq systemd unit file during boot
  systemd:
    name: dnsmasq
    enabled: no
