- include_tasks: detected_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- include_tasks: computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- name: Set hostname
  template: dest=/etc/hostname
            src=network/hostname.j2
            owner=root
            mode=0644
  when: is_debuntu
  register: hostname_change
  tags:
    - network
    - domain

- name: Configure /etc/sysconfig/network
  template: src=network/sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644
  when: is_redhat
  register: hostname_change
  tags:
    - network
    - domain

- name: Create iiab_domain_name flag
  template: src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - iiab_domain_name
  tags:
    - network
    - domain

##### Start static ip address info for first run #####
#- include_tasks: static.yml
#  when: 'iiab_wan_iface != "none" and wan_ip != "dhcp"'
##### End static ip address info

- include_tasks: hosts.yml
  tags:
    - network
    - domain

- include_tasks: named.yml
  tags:
    - network
    - named

- include_tasks: dhcpd.yml
  tags:
    - dhcpd
    - dnsmasq
    - squid
    - domain
#  when: hostname_change.changed or installing

- include_tasks: squid.yml
  tags:
    - network

#### end install portion
#### start network layout
# setting installing would skip configuring network
# but would configure but not start services
#- include: computed_network.yml
#  when: not installing
#  tags:
#    - network
#    - network-discover

- include_tasks: wondershaper.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

- include_tasks: iptables.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

- include_tasks: avahi.yml
  tags:
    - network

- include_tasks: ifcfg_mods.yml
  tags:
    - network

- include_tasks: debian.yml
  tags:
    - network
  when: is_debuntu and not is_rpi  and not installing

- include_tasks: rpi_debian.yml
  tags:
    - network
  when: is_debuntu and is_rpi  and not installing

- name: Create IIAB network flags
  template: src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - iiab_wan_device
    - iiab_lan_device
  when: not installing
  tags:
    - network

- include_tasks: computed_services.yml
  tags:
    - network

- include_tasks: enable_services.yml
  tags:
    - network

- include_tasks: restart.yml
  when: not installing
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid
#### end services
