---
- name: Install Transmission daemon and cli-tools.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - transmission-daemon
    - transmission-cli

- name: Add transmission to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: transmission
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: transmission
    - option: description
      value: '"Transmission is a set of lightweight BitTorrent clients (in GUI, CLI and daemon form)."'
    - option: transmission_enabled
      value: "{{ transmission_enabled }}"
    - option: transmission_install
      value: "{{ transmission_install }}"
