# INSTALL 3 PREREQS

- name: "Set 'nodejs_install: True' and 'nodejs_enabled: True'"
  set_fact:
    nodejs_install: True
    nodejs_enabled: True

- name: Install Node.JS
  include_role:
    name: nodejs

- name: "Set 'yarn_install: True' and 'yarn_enabled: True'"
  set_fact:
    yarn_install: True
    yarn_enabled: True

- name: Install Yarn
  include_role:
    name: yarn

- name: Install package 'libsecret-1-dev'
  package:
    name: libsecret-1-dev
    state: present

# CREATE 2 DIRS & RUN YARN

- name: mkdir {{ internetarchive_dir }}
  file:
    path: "{{ internetarchive_dir }}"    # /opt/iiab/internetarchive
    state: directory
    owner: "root"

- name: Run yarn install to get needed modules (CAN TAKE ~15 MINUTES)
  shell: yarn config set child-concurrency 1 && yarn add @internetarchive/dweb-mirror
  args:
    chdir: "{{ internetarchive_dir }}"
    creates: "{{ internetarchive_dir }}/node_modules/@internetarchive/dweb-mirror/internetarchive"
  when: internet_available | bool
  register: internetarchive_installing

- name: mkdir /library/archiveorg
  file:
    path: "/library/archiveorg"
    state: directory
    owner: "root"

# CONFIG FILES

- name: "Install from templates: internetarchive.service (systemd), internetarchive.conf (Apache)"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: root
    group: root
  with_items:
    - { src: 'internetarchive.service.j2', dest: '/etc/systemd/system/internetarchive.service' }
    - { src: 'internetarchive.conf', dest: '/etc/apache2/sites-available/internetarchive.conf' }


# RECORD Internet Archive AS INSTALLED

- name: "Set 'internetarchive_installed: True'"
  set_fact:
    internetarchive_installed: True

- name: "Add 'internetarchive_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    dest: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^internetarchive_installed'
    line: 'internetarchive_installed: True'
