# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "internetarchive_install is sameas true" (boolean not string etc)
  assert:
    that: internetarchive_install is sameas true
    fail_msg: "PLEASE SET 'internetarchive_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "internetarchive_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: internetarchive_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'internetarchive_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


#- name: Set --reinstall fact
#  set_fact:
#    internetarchive_upgrade: True
#  when: reinstall is defined

- block:    # UPDATE IF... internetarchive_installed is defined and internet_available

  - name: Stop 'internetarchive' systemd service, if internetarchive_upgrade
    systemd:
      name: internetarchive
      daemon_reload: yes
      state: stopped
    #when: internetarchive_enabled and internetarchive_upgrade

  - name: Update pre-existing install (yarn upgrade) if internetarchive_upgrade
    shell: yarn config set child-concurrency 1 && yarn install && yarn upgrade
    args:
      chdir: "{{ internetarchive_dir }}"
    #when: internetarchive_enabled and internetarchive_upgrade

  when: internetarchive_installed is defined and internet_available   # END BLOCK

# "ELSE" INSTALL...

- name: Install Internet Archive if 'internetarchive_installed' not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: internetarchive_installed is undefined and internet_available



# ENABLE/DISABLE/RESTART SYSTEMD SERVICE & WEB SERVERS AS NEC ?

- name: Enable & Restart 'internetarchive' systemd service, if internetarchive_enabled
  systemd:
    name: internetarchive
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: internetarchive_enabled | bool

- name: Disable & Stop 'internetarchive' systemd service, if not internetarchive_enabled
  systemd:
    name: internetarchive
    enabled: no
    state: stopped
  when: not internetarchive_enabled

#- name: Enable/Disable/Restart Apache if primary
- name: SHIM FOR NOW SO ALWAYS DO THE...Enable/Disable/Restart Apache
  include_tasks: apache.yml
  #when: not nginx_enabled

- name: Enable/Disable/Restart NGINX if primary
  include_tasks: nginx.yml
  when: nginx_enabled | bool


- name: Add 'internetarchive' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: internetarchive
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Internet Archive
    - option: description
      value: '"Take the Internet Archive experience and materials offline, in a decentralized way!"'
    - option: internetarchive_install
      value: "{{ internetarchive_install }}"
    - option: internetarchive_enabled
      value: "{{ internetarchive_enabled }}"
