- name: Does systemd iiab-startup.service exist?
  stat:
    path: "{{ systemd_location }}/iiab-startup.service"
  register: startup_unit

- name: Copy iiab-startup.service to /etc/systemd/system
  template:
    src: iiab-startup.service
    dest: /etc/systemd/system/
  when: startup_unit.stat.exists is defined and not startup_unit.stat.exists

- name: Copy template script to /usr/libexec/iiab-startup.sh
  template:
    src: iiab-startup.sh
    dest: /usr/libexec/
    mode: 0755
  when: startup_unit.stat.exists is defined and not startup_unit.stat.exists

- name: Do a systemd daemon-reload
  # shell: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: startup_unit.stat.exists is defined and not startup_unit.stat.exists

- name: Enable & restart the systemd service
  # shell: systemctl restart iiab-startup.service
  # shell: systemctl enable iiab-startup.service
  service:
    enabled: yes
    restarted: yes
  when: startup_unit.stat.exists is defined and not startup_unit.stat.exists
