- name: '2021-07-27: SEE ALSO ~3 networking packages EARLIER installed by https://github.com/iiab/iiab/blob/master/roles/1-prep/tasks/raspberry_pi.yml'
  meta: noop

- name: '2021-07-27: SEE ALSO ~3 networking packages EARLIER installed by https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml'
  meta: noop

- name: Install package networkd-dispatcher (OS's other than RaspiOS)
  package:
    name: networkd-dispatcher
    state: present
  when: not is_raspbian

- name: 'Install network packages: hostapd, iproute2, iptables-persistent, netmask (debuntu) -- later used by https://github.com/iiab/iiab/tree/master/roles/network'
  package:
    name:
      - iproute2
      - iptables-persistent
      - hostapd
      - netmask
    state: present

- name: Install /etc/network/if-pre-up.d/iptables from template (0755, debuntu)
  template:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
    mode: '0755'
