- name: Install yum/dnf packages (redhat)
  package:
    name:
      - yum-utils
      - createrepo
      - wpa_supplicant
      - linux-firmware
      - syslog
      - xml-common
      - nss-mdns
      - avahi
      - avahi-tools
    state: present
  when: is_redhat

- name: Download & install usbmount, missing from Debian Stretch (debian-9)
  apt:
    deb: "{{ iiab_download_url }}/usbmount_0.0.14.1_all.deb"
    #timeout: "{{ download_timeout }}"    # Ansible's apt module doesn't support timeout parameter; that's ok as usbmount_0.0.14.1_all.deb is only 10KB
  when: internet_available and is_debian_9

- name: Install packages (debuntu)
  package:
    name:
      - inetutils-syslogd
      - wpasupplicant
      - libnss-mdns
      - avahi-daemon
      - avahi-discover
      - exfat-fuse
      - exfat-utils
    state: present
  when: is_debuntu

- name: Install common packages
  package:
    name:
      - acpid
      - mlocate
      - rsync
      - htop
      #- etckeeper    # "nobody is really using etckeeper and it's bloating the filesystem every time apt runs" per @jvonau at https://github.com/iiab/iiab/issues/1146
      - python-passlib
      - usbmount
      - net-tools
      - openssh-server
      - sudo
      - logrotate
      - make
      - tar
      - unzip
      - bzip2
      - i2c-tools
      - bridge-utils
      - netmask
      - usbutils
      - hostapd
      - wget
      - openssl    # FC 18 does not supply, but pear requires
      - gawk
      - curl
      - pandoc
      - lynx    # already installed by 1-prep's roles/iiab-admin/tasks/access.yml
      - ntfs-3g
    state: present

- name: Install common Python packages {python-pip, python-setuptools, python-virtualenv}
  package:
    name:
      - python-pip
      - python-setuptools
      - python-virtualenv
    state: present
