- name: Enable & (Re)Start remote.it's connectd daemon which calls home
  systemd:
    name: connectd
    daemon_reload: yes
    enabled: yes
    state: restarted    
  when: remoteit_enabled

- name: Find the uuid for the connector
  shell: ls /etc/systemd/system/multi-user.target.wants/ | grep remoteit
  register: remoteit_service
  ignore_errors: yes

- name: Stop the uuid {{ remoteit_service.stdout }}
  systemd:
    name: "{{ remoteit_service.stdout }}"
    enabled: no
    state: stopped
  when: not remoteit_enabled and not remoteit_service.stdout == ""

- name: Disable & Stop remote.it's connectd daemon
  systemd:
    name: connectd
    enabled: no
    state: stopped
  when: not remoteit_enabled
