
- name: Enable & (Re)Start connectd daemon which calls home
  systemd:
    name: connectd
    daemon_reload: yes
    enabled: yes
    state: restarted    
  when: remoteid_enabled

- name: Disable & Stop connectd daemon
  systemd:
    name: connectd
    enabled: no
    state: stopped
  when: not remoteit_enabled

