- name: Enable & (Re)Start remote.it's connectd daemon which calls home
  systemd:
    name: connectd
    daemon_reload: yes
    enabled: yes
    state: restarted    
  when: remoteit_enabled

- name: Disable & Stop remote.it's connectd daemon
  systemd:
    name: connectd
    enabled: no
    state: stopped
  when: not remoteit_enabled
