- name: Download the command line interface for this device
  get_url:
      url: '{{ remoteit_cli_url }}'
      dest: /usr/bin/
      mode: 0755

- name: Install the device package
  apt:
      deb: '{{ remoteit_device_url }}'
      state: present

# RECORD remoteit AS INSTALLED

- name: "Set 'openvpn_installed: True'"
  set_fact:
    remoteit_installed: True

- name: "Add 'remoteit_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^remoteit_installed'
    line: 'remoteit_installed: True'
