# The values here are defaults.
# To override them edit /etc/iiab/local_vars.yml

# Installation Variables
calibre-web_install: False
calibre-web_enabled: False

# calibre-web folder to store its data and configuration files.
calibre-web_home: "{{ content_base }}/calibre-web"

calibre-web_http_port: 8083
calibre-web_url: /calibre-web
calibre-web_path: "{{ iiab_base }}/calibre-web"
calibre-web_exec_path:  "{{ calibre-web_path }}/cps.py"

# Calibre-web setup will be provisioned with default administration account, metadata.db and
# language. You could turn this to 'False' while reinstalling/upgrading calibre-web.
calibre-web_provision: True

#calibre-web system user
calibre-web_user: root

# calibre-web admin account
# calibre-web_admin_user: admin
# calibre-web_admin_password: admin123
