# The values here are defaults.
# To override them edit /etc/iiab/local_vars.yml

# Installation Variables
calibreweb_install: False
calibreweb_enabled: False

calibreweb_port: 8083
calibreweb_url: /calibre-web
calibreweb_path: "{{ iiab_base }}/calibre-web"
calibreweb_exec_path: "{{ calibreweb_path }}/cps.py"

# calibre-web folder to store its data files.
calibreweb_home: "{{ content_base }}/calibre-web"
# calibre-web folder to store configuration files.
calibreweb_config: "{{ calibreweb_home }}/config"

# Calibre-web setup will be provisioned with default administration account, metadata.db and
# language. You could turn this to 'False' while reinstalling/upgrading calibre-web.
calibreweb_provision: True
calibreweb_settings_database: app.db
calibreweb_database: metadata.db

#calibre-web system user
calibreweb_user: root

# calibreweb admin account
# calibreweb_admin_user: Admin
# calibreweb_admin_password: changeme
