- name: Enable http://box{{ kiwix_url }} via Apache
  command: a2ensite kiwix.conf
  when: apache_install and kiwix_enabled

- name: Disable http://box{{ kiwix_url }} via Apache
  command: a2dissite kiwix.conf
  when: apache_install and not kiwix_enabled

- name: Restart Apache systemd service ({{ apache_service }})
  systemd:
    name: "{{ apache_service }}"
    daemon-reload: yes
    state: restarted
  when: apache_enabled | bool
