- name: Enable & Restart 'kiwix-serve' systemd service
  systemd:
    daemon_reload: yes
    name: kiwix-serve
    enabled: yes
    state: restarted
  when: kiwix_enabled | bool

- name: Disable 'kiwix-serve' systemd service
  systemd:
    name: kiwix-serve
    enabled: no
    state: stopped
  when: not kiwix_enabled

# TO DO: BOTH CRON ENTRIES BELOW *SHOULD* BE DELETED "when: not kiwix_enabled"

# In the past kiwix-serve did not stay running, so we'd been doing this hourly.
# @mgautierfr & others suggest kiwix-serve might be auto-restarted w/o cron in
# future, whenever service fails, if this really catches all cases??
# https://github.com/iiab/iiab/issues/484#issuecomment-342151726
- name: Make a crontab entry to restart kiwix-serve at 4AM (debuntu)
  lineinfile:
         # mn hr dy mo day-of-week[Sunday=0] username command-to-be-executed
    line: "0  4  *  *  * root /bin/systemctl restart kiwix-serve.service"
    dest: /etc/crontab
  when: kiwix_enabled and is_debuntu

- name: Make a crontab entry to restart kiwix-serve at 4AM (redhat)
# *  *  *  *  * user-name  command to be executed
  lineinfile:
         # mn hr dy mo day-of-week[Sunday=0] username command-to-be-executed
    line: "0  4  *  *  * root /usr/bin/systemctl restart kiwix-serve.service"
    dest: /etc/crontab
  when: kiwix_enabled and is_redhat

# Apache

- name: Enable http://box/kiwix with Apache proxy
  command: a2ensite kiwix.conf
  when: kiwix_enabled and not nginx_enabled

- name: Disable http://box/kiwix with Apache
  command: a2dissite calibre-web.conf
  when: not kiwix_enabled or nginx_enabled

- name: Restart Apache systemd service ({{ apache_service }})
  systemd:
    name: "{{ apache_service }}"
    daemon-reload: yes
    state: restarted
  when: not nginx_enabled

# NGINX

- name: 'Install from template: {{ nginx_config_dir }}/kiwix-nginx.conf'
  template:
    src: kiwix-nginx.conf
    dest: "{{ nginx_config_dir }}/kiwix-nginx.conf"
    owner: root    # Not nec? Remove?
    group: root    # Not nec? Remove?
    mode: '0644'    # Not nec? Remove?
  when: kiwix_enabled and nginx_enabled

- name: Remove {{ nginx_config_dir }}/kiwix-nginx.conf
  file:
    path: "{{ nginx_config_dir }}/kiwix-nginx.conf"
    state: absent
  when: not kiwix_enabled or not nginx_enabled

- name: Restart nginx systemd service
  systemd:
    name: nginx
    daemon-reload: yes
    state: restarted
  when: nginx_enabled | bool

- name: Add 'kiwix' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: kiwix
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: name
    value: Kiwix
  - option: description
    value: '"Part of https://github.com/kiwix/kiwix-tools/ - kiwix-serve is the most used web server for ZIM files."'
  - option: kiwix_url
    value: "{{ kiwix_url }}"
  - option: kiwix_path
    value: "{{ kiwix_path }}"
  - option: kiwix_port
    value: "{{ kiwix_port }}"
  - option: iiab_zim_path
    value: "{{ iiab_zim_path }}"
  - option: kiwix_library_xml
    value: "{{ kiwix_library_xml }}"
  - option: kiwix_enabled
    value: "{{ kiwix_enabled }}"
