# EXPERIMENTAL i686 CODE PATH
- name: Set kiwix source file name i686
  set_fact:
     kiwix_src_file: "{{ kiwix_src_file_i686 }}"
     kiwix_src_bin_only: False
  when: ansible_machine == "i686"

- name: "Set Kiwix filename to d/l: {{ kiwix_src_file_linux64 }} (x86_64)"
  set_fact:
     kiwix_src_file: "{{ kiwix_src_file_linux64 }}"
     kiwix_src_bin_only: True
  when: ansible_machine == "x86_64"

- name: "Set Kiwix filename to d/l: {{ kiwix_src_file_armhf }} (armv6l or armv71)"
  set_fact:
     kiwix_src_file: "{{ kiwix_src_file_armhf }}"
     kiwix_src_bin_only: True
  when: ansible_machine == "armv7l" or ansible_machine == "armv6l"

- name: Download the Kiwix software to /opt/iiab/downloads
  get_url:
    url: "{{ iiab_download_url }}/{{ kiwix_src_file }}"
    dest: "{{ downloads_dir }}/{{ kiwix_src_file }}"
  when: internet_available

- include_tasks: kiwix_install.yml
  when: kiwix_src_file is defined
  tags:
    - kiwix

- debug:
    msg: "WARNING kiwix source is not defined for your platform"
  when: not kiwix_src_file
