sugarizer_install: True
sugarizer_enabled: False

sugarizer_location: {{ iiab_base }}    # /opt/iiab

sugarizer_version: sugarizer-1.0
sugarizer_git_version: v1.0.1

sugarizer_server_version: sugarizer-server-1.0
sugarizer_server_git_version: v1.0

npm_exists: False
