sugarizer_install: True
sugarizer_enabled: False

sugarizer_location: {{ iiab_base }}    # /opt/iiab

sugarizer_version: sugarizer-1.0
sugarizer_git_version: v1.0.1
# PLEASE HELP MONITOR https://github.com/llaske/sugarizer/releases FOR
# STABLE/OFFICIAL RELEASES!

sugarizer_server_version: sugarizer-server-1.0
sugarizer_server_git_version: master
# CLONING SUGARIZER-SERVER'S MASTER BRANCH IS NOT A LONG-TERM SOLUTION,
# SO LET'S MONITOR https://github.com/llaske/sugarizer-server/releases
# FOR A MORE STABLE/OFFICIAL RELEASE DURING MID-2018!

node_modules_exists: False
