sugarizer_install: False
sugarizer_enabled: False

sugarizer_location: "{{ iiab_base }}"    # /opt/iiab

sugarizer_dir_version: sugarizer-1.1.0    # WAS: sugarizer-1.0, sugarizer-master
sugarizer_git_version: v1.1.0             # WAS: v1.0.1, master
# PLEASE HELP MONITOR https://github.com/llaske/sugarizer/releases

sugarizer_server_dir_version: sugarizer-server-dev    # WAS: sugarizer-server-1.0, sugarizer-server-master
sugarizer_server_git_version: dev                     # WAS: v1.0.1, master
# PLEASE HELP MONITOR https://github.com/llaske/sugarizer-server/releases
