# 2022-07-22: SIMILAR TO roles/www_options/tasks/main.yml FOR browser
#                    AND roles/network/tasks/netwarn.yml  FOR iiab-network


- name: Install /etc/profile.d/iiab-pwdwarn-profile.sh from template, to issue warnings (during shell/ssh logins) if iiab-admin password is the default
  template:
    src: iiab-pwdwarn-profile.sh.j2
    dest: /etc/profile.d/iiab-pwdwarn-profile.sh
    mode: '0644'

- name: Does /home/{{ iiab_admin_user }}/.config/wayfire.ini exist?
  stat:
    path: /home/{{ iiab_admin_user }}/.config/wayfire.ini
  register: wayfire_ini

- name: "If so, install from template: /usr/local/sbin/iiab-pwdwarn-wayfire"
  template:
    src: iiab-pwdwarn-wayfire.j2
    dest: /usr/local/sbin/iiab-pwdwarn-wayfire
    mode: '0755'
  when: wayfire_ini.stat.exists

# 2019-03-07: This pop-up (/etc/xdg/lxsession/LXDE-pi/sshpwd-lxde-iiab.sh) did
# not actually appear when triggered by /etc/xdg/autostart/pprompt-iiab.desktop
# (or pprompt.desktop as Raspbian has working since 2018-11-13!)  Too bad as it
# would be really nice to standardize pop-ups across Ubermix & all distros...
# Is this a permissions/security issue presumably?  Official autostart spec is:
# https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html
# Raspbian's 2016-2018 evolution here: https://github.com/iiab/iiab/issues/1537

- name: ...and put a line in /home/{{ iiab_admin_user }}/.config/wayfire.ini to trigger pop-ups
  ini_file:
    path: /home/{{ iiab_admin_user }}/.config/wayfire.ini    # iiab-admin
    section: autostart
    option: iiab-pwdwarn-wayfire
    value: /usr/local/sbin/iiab-pwdwarn-wayfire
  when: wayfire_ini.stat.exists
