# Local Add-ons

- name: ...IS BEGINNING ====================================
  meta: noop

- name: AZURACAST
  include_role:
    name: azuracast
  when: azuracast_install

# Porting to Python 3 is complete: does this belong elsewhere?
- name: CAPTIVE PORTAL
  include_role:
    name: captiveportal
  when: captiveportal_install

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  when: internetarchive_install

- name: MINETEST
  include_role:
    name: minetest
  when: minetest_install

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install and ansible_machine is search("64")    # 2022-11-10: Avoid installing on 32-bit, until RasPiOS fixes Rust (PR #3421)

# KEEP NEAR THE VERY END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install

# Pulls in a large number of devel packages, via asterisk.yml -> 'install_prereq install'
# https://github.com/asterisk/asterisk/blob/master/contrib/scripts/install_prereq#L21-L35
- name: PBX - Asterisk & FreePBX
  include_role:
    name: pbx
  when: pbx_install

- name: "INSTALL python3-pip FOR ADMIN CONSOLE 'cmdsrv : Download speedtest-cli' -- SEE PR #3494 -- REMOVE THIS CODE LATER"
  package:
    name: python3-pip
    state: present

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
