# Local Add-ons

- name: ...IS BEGINNING ====================================
  command: echo

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  when: internetarchive_install | bool

# Is porting to Python 3 complete, and if so does this belong elsewhere?
- name: CAPTIVE PORTAL
  include_role:
    name: captiveportal
  when: captiveportal_install | bool

- name: MINETEST
  include_role:
    name: minetest
  when: minetest_install | bool

# KEEP AT THE END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install | bool

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install | bool

- name: '2020-05-21: TEMPORARILY INSTALL APACHE UNTIL ADMIN CONSOLE DECLARES (OR REMOVES?) ITS DEPENDENCY within [console : Enable ssl] to avoid error "Neither of apache2ctl nor apachctl found. At least one apache control binary is necessary." -- possibly var adm_cons_force_ssl is still useful here?'
  package:
    name: apache2
  when: admin_console_install | bool

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
