# Local Add-ons

- name: ...IS BEGINNING ====================================
  command: echo

- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install
  tags: calibre

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install
  tags: calibre-web

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=9'
    state: present
