# Local Add-ons

- name: ...IS BEGINNING ====================================
  command: echo

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  when: internetarchive_install | bool
  tags: internetarchive

- name: MINETEST
  include_role:
    name: minetest
  when: minetest_install | bool
  tags: minetest

# KEEP AT THE END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install | bool
  tags: calibre

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install | bool
  tags: calibre-web

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
    state: present
