# Local Add-ons

- name: ...IS BEGINNING ====================================
  meta: noop

- name: AZURACAST
  include_role:
    name: azuracast
  when: azuracast_install

# Porting to Python 3 is complete: does this belong elsewhere?
- name: CAPTIVE PORTAL
  include_role:
    name: captiveportal
  when: captiveportal_install

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  when: internetarchive_install

- name: MINETEST
  include_role:
    name: minetest
  when: minetest_install

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install

# KEEP NEAR THE VERY END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install

# Pulls in a large number of devel packages, via asterisk.yml -> 'install_prereq install'
# https://github.com/asterisk/asterisk/blob/master/contrib/scripts/install_prereq#L21-L35
- name: PBX - Asterisk & FreePBX
  include_role:
    name: pbx
  when: pbx_install

- name: Read 'disk_space_a_priori' from /etc/iiab/iiab.ini
  set_fact:
    df1: "{{ lookup('ansible.builtin.ini', 'disk_space_a_priori', section='summary', file=iiab_ini_file) }}"

- name: Record currently available disk space, to compare with original 'disk_space_a_priori'
  shell: df -PB1 $(findmnt / -o SOURCE -n) | awk 'NR==2 {print $4}'
  register: df2

- name: Add ESTIMATED 'iiab_software_disk_usage = {{ df1|int - df2.stdout|int }}' to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: summary
    option: iiab_software_disk_usage
    value: "{{ df1|int - df2.stdout|int }}"

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
