# Local Add-ons

- name: ...IS BEGINNING ====================================
  command: echo

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  #tags: internetarchive

# Is porting to Python 3 complete?
- name: CAPTIVE PORTAL
  include_tasks: roles/captiveportal/tasks/main.yml
  when: captiveportal_install | bool
  #tags: base, captiveportal, network, domain

- name: MINETEST
  include_role:
    name: minetest
  #tags: minetest

# KEEP AT THE END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  #tags: calibre

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  #tags: calibre-web

# Could split these two below to Stage 10?

- name: Configure NGINX (already installed in Stage 3-BASE-SERVER)
  # If just CONFIGURING, should we use one of the following instead ??
  # include_tasks: roles/nginx/tasks/setup.yml
  # include_tasks: roles/nginx/tasks/enable.yml
  include_role:
    name: nginx
  when: nginx_install | bool
  #tags: base, nginx

- name: Configure Apache systemd service ({{ apache_service }})
  include_role:
    name: httpd-enable
  when: apache_install | bool
  #tags: base, httpd

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
    state: present
