- name: Install Matomo main
  include_tasks: install.yml
  vars:
    mdb_dbname: "matomodb"
    mdb_username: "mariadb_admin"
    mdb_password: "pw_set_by_ansible"
    host_url: "http://{{ ansible_default_ipv4.address}}"
    matomo_url: "{{ host_url }}/matomo/"
    matomo_cronjob: "sudo python3 /library/www/html/matomo/misc/log-analytics/import_logs.py --url={{ matomo_url }} --idsite=1 --recorders=4 --enable-http-errors --enable-http-redirects --enable-static --enable-bots /var/log/nginx/access.log"
