# 0. CLEAN UP PRIOR VERSIONS OF SUGARIZER (NEEDS WORK!)

- name: Wipe /library/www/html/sugarizer* if sugarizer-1.0
  shell: "rm -rf {{ doc_root }}/sugarizer*"
  when: sugarizer_version == "sugarizer-1.0"

# 1. DOWNLOAD /opt/iiab/sugarizer

# July 2018: instead let's "git clone" IIAB's specified/preferred version
#- name: D/L latest stable Sugarizer from location we control to /opt/iiab/downloads/
#  get_url:
#    url: "{{ iiab_download_url }}/{{ sugarizer_version }}.tar.gz"
#    dest: "{{ downloads_dir }}/{{ sugarizer_version }}.tar.gz"
#    timeout: "{{ download_timeout }}"
#  when: internet_available
#
#- name: Untar to /opt/iiab/{{ sugarizer_version }}
#  unarchive:
#    src: "{{ downloads_dir }}/{{ sugarizer_version }}.tar.gz"
#    dest: "{{ sugarizer_location }}"
#    creates: "{{ sugarizer_location }}/{{ sugarizer_version }}/index.html"
##  command: tar xzf {{ downloads_dir }}/{{ sugarizer_version }}.tar.gz -C {{ sugarizer_location }}
##           creates="{{ sugarizer_location }}/{{ sugarizer_version }}/index.html"

- name: Clone llaske/sugarizer ({{ sugarizer_git_version }}) from GitHub to /opt/iiab
  git:
    repo: https://github.com/llaske/sugarizer
    dest: "{{ sugarizer_location }}/{{ sugarizer_version }}"
    version: "{{ sugarizer_git_version }}"
  when: internet_available

#- name: Move /opt/iiab/sugarizer to /opt/iiab/{{ sugarizer_version }}
#  command: mv "{{ sugarizer_location }}/sugarizer" "{{ sugarizer_location }}/{{ sugarizer_version }}"
#  args:
#    creates: "{{ sugarizer_location }}/{{ sugarizer_version }}"

- name: Create symbolic link /opt/iiab/sugarizer -> /opt/iiab/{{ sugarizer_version }}
  file:
    src: "{{ sugarizer_location }}/{{ sugarizer_version }}"
    dest: "{{ sugarizer_location }}/sugarizer"
    state: link

# 2. DOWNLOAD /opt/iiab/sugarizer-server

# July 2018: instead let's "git clone" IIAB's specified/preferred version
# Tarfile below was not working, as documented at:
#    https://github.com/iiab/iiab/issues/798
#    https://github.com/iiab/iiab/issues/814
#- name: Download latest stable Server from location we control
#  get_url:
#    url: "{{ iiab_download_url }}/{{ sugarizer_server_version }}.tar.gz"
#    dest: "{{ downloads_dir }}/{{ sugarizer_server_version }}.tar.gz"
#    timeout: "{{ download_timeout }}"
#  when: internet_available
#
#- name: Untar to /opt/iiab/{{ sugarizer_server_version }}
#  unarchive:
#    src: "{{ downloads_dir }}/{{ sugarizer_server_version }}.tar.gz"
#    dest: "{{ sugarizer_location }}"
#    creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/index.html"

- name: Clone llaske/sugarizer-server ({{ sugarizer_server_git_version }}) from GitHub to /opt/iiab
  git:
    repo: https://github.com/llaske/sugarizer-server
    dest: "{{ sugarizer_location }}/{{ sugarizer_server_version }}"
    version: "{{ sugarizer_server_git_version }}"
  when: internet_available

#- name: Move /opt/iiab/sugarizer-server to /opt/iiab/{{ sugarizer_server_version }}
#  command: mv "{{ sugarizer_location }}/sugarizer-server" "{{ sugarizer_location }}/{{ sugarizer_server_version }}"
#  args:
#    creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}"

- name: Create symbolic link /opt/iiab/sugarizer-server -> /opt/iiab/{ sugarizer_server_version }}
  file:
    src: "{{ sugarizer_location }}/{{ sugarizer_server_version }}"
    dest: "{{ sugarizer_location }}/sugarizer-server"
    state: link

# 3. INSTALL A GOOD VERSION OF Node.js AND npm

# Both Raspbian and Debian 9 STILL need this approach as of 2018-07-11,
# as documented at https://github.com/iiab/iiab/issues/798#issuecomment-404324530
- name: Set up Node.js 8.x apt sources (debuntu but avoid ubuntu-18)
  shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -
  when: internet_available and is_debuntu and not is_ubuntu_18

- name: Install latest Node.js which includes /usr/bin/npm (debuntu but avoid ubuntu-18)
  package:
    name: nodejs
    # name: nodejs=8.x
    state: latest
    # state: present
  when: internet_available and is_debuntu and not is_ubuntu_18

- name: Install Node.js and npm (ubuntu-18)
  package:
    name: "{{ item }}"
    state: latest
  when: internet_available and is_ubuntu_18
  with_items:
    - nodejs
    - npm

- name: Install npm (OS's other than debuntu)
  package:
    name: "{{ item }}"
    state: present
  when: internet_available and not is_debuntu
  with_items:
    - nodejs
    - npm

# 4. RUN "npm install" TO POPULATE ~35MB /opt/iiab/sugarizer-server/node_modules

# re-running "npm install" fails on Raspbian 9
- name: Check for Sugarizer already installed
  stat:
    path: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/node_modules"
  register: nmtest
  ignore_errors: true

- name: Set a flag to abort second attempt to install
  set_fact:
    node_modules_exists: True
  when: nmtest.stat is defined and nmtest.stat.exists

- name: Create the express framework for Node.js (OS's other than Fedora 18)
  shell: npm install
  args:
    chdir: "{{ sugarizer_location }}/{{  sugarizer_server_version }}"
    creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/node_modules"
    #creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/server/node_modules"
  when: not is_F18 and not node_modules_exists

- name: Create the express framework for Node.js (Fedora 18)
  shell: npm install
  args:
    chdir: "{{ sugarizer_location }}/sugarizer/server"
  when: is_F18 and not node_modules_exists

# 5. PLACE CONFIG FILES

- name: Create systemd files and copy our ini file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: 'sugarizer.service.j2', dest: '/etc/systemd/system/sugarizer.service', mode: '0644' }
    - { src: 'sugarizer.ini', dest: '{{ sugarizer_location }}/{{ sugarizer_server_version }}/env/sugarizer.ini', mode: '0644' }
    - { src: 'sugarizer.conf', dest: '/etc/apache2/sites-available', mode: '0644' }

- name: Create symlink enabling short URL http://box/sugarizer
  file:
    src: /etc/apache2/sites-available/sugarizer.conf
    dest: /etc/apache2/sites-enabled/sugarizer.conf
    state: link

# 6. RESTART/STOP SYSTEMD SERVICE

- name: Enable services (all OS's)
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: restarted
  with_items:
    - { name: mongodb }
    - { name: sugarizer }
  when: sugarizer_enabled

- name: Disable services (all OS's)
  service:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  with_items:
    - { name: sugarizer }
  when: not sugarizer_enabled

- name: Add 'sugarizer' to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: sugarizer
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: Sugarizer
    - option: description
      value: '"The Sugar Learning Platform began with the famous One Laptop Per Child project, written in Python. Sugarizer is the new HTML/JavaScript implementation of Sugar, usable in most all browsers."'
    - option: enabled
      value: "{{ sugarizer_enabled }}"
