- name: Install 'sugarizer' if sugarizer_install and not Debian 10+
  include_tasks: install.yml
  when: sugarizer_install and not ((is_debian and not is_raspbian) and (not is_debian_8) and (not is_debian_9))
