# 2019-01-16: @jvonau's PR #1403 moved installation of Node.js (8.x for now) &
# npm to roles/nodejs/tasks/main.yml, triggered by roles/nodered/meta/main.yml

- name: 'npm install node-red packages globally: node-red, node-red-admin, node-red-dashboard'
  shell: npm install -g --unsafe-perm node-red node-red-admin node-red-dashboard
  when: nodered_install

- name: Ensure Linux group "nodered" exists
  group:
    name: nodered
    state: present
  when: nodered_install

- name: Ensure Linux user "nodered" exists and is added to group "nodered"
  user:
    name: nodered
    group: nodered
  when: nodered_install

- name: Create /home/nodered/.node-red/ directory
  file:
    path: /home/nodered/.node-red
    state: directory
    owner: nodered
    group: nodered
    mode: 0775
  when: nodered_install

- name: Install /home/nodered/.node-red/settings.js from template, with authentication
  template:
    backup: yes
    src: settings.js.j2
    dest: /home/nodered/.node-red/settings.js
    owner: nodered
    group: nodered
    mode: 0755
  when: nodered_install

- name: Install /etc/systemd/system/node-red.service systemd unit file from template
  template:
    backup: yes
    src: node-red.service.j2
    dest: /etc/systemd/system/node-red.service
    owner: root
    group: root
    mode: 0666
  when: nodered_install

- name: Enable & Start node-red service
  systemd:
    daemon_reload: yes
    name: node-red
    enabled: yes
    state: started
  when: nodered_enabled
