users:
  - name: azureuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$XQyU87E.7wiU81vn$1VHIRQxQhTp0SH0sxkSvH5pPRv2OEihDfq9d6dpOjOHK/HMjb8GvqmKkGKqiln50UCRq/AS5TcYp4uynts9q1/
    packages: git
    runcmd:
      - [git, clone, -b, deploy_24hrs, https://github.com/Akatama/iiab.git]
      - [sudo, mkdir, /opt/iiab/]
      - [sudo, mv, ./iiab, /opt/iiab]
      - [sudo, mkdir, /etc/iiab]
      - [sudo, cp, /opt/iiab/iiab/vars/local_vars_small_maps.yml, /etc/iiab/local_vars.yml]
      - [cd, /opt/iiab/iiab]
      - [sudo, ./scripts/ansible]
      - [sudo, ./iiab-install]
