# Base Server

- name: ...IS BEGINNING =====================================
  command: echo

- name: MYSQL
  include_role:
    name: mysql
  when: mysql_install | bool

# 2020-05-16: Invoked as nec by 5 roles {cups, elgg, lokole, moodle, nodered}.
# These 9 roles conditionally touch Apache .conf files etc: awstats, calibre-
# web, kalite, kiwix, nextcloud, sugarizer, usb_lib, wordpress, www_options.
# CAUTION: mysql/tasks/install.yml's php install drags in apache2 regardless !
#
# - name: HTTPD (Apache)
#   include_role:
#     name: httpd
#   when: apache_install | bool

- name: NGINX
  include_role:
    name: nginx
  when: nginx_install | bool

- name: WWW_BASE (WWW_OPTIONS should be installed later)
  include_role:
    name: www_base

- name: Recording STAGE 3 HAS COMPLETED =====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=3'
