# Base Server

- name: ...IS BEGINNING =====================================
  command: echo

- name: HTTPD (APACHE)
  include_role:
    name: httpd
  # has no "when: XXXXX_install" flag
  tags: base, httpd

- name: MYSQL
  include_role:
    name: mysql
  # has no "when: XXXXX_install" flag
  tags: base, mysql

- name: Restart httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: not installing

- name: Recording STAGE 3 HAS COMPLETED =====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=3'
    state: present
