# Base Server

- name: ...IS BEGINNING =====================================
  command: echo

- name: MYSQL
  include_role:
    name: mysql
  when: mysql_install | bool

# 2020-05-20: Apache role 'httpd' is installed as nec by any of these 6 roles:
# cups, elgg, lokole, moodle, nodered, phpmyadmin.
#
# These 14 roles conditionally touch Apache .conf files etc: awstats,
# calibre-web, gitea, internetarchive, kalite, kiwix, kolibri, mediawiki,
# munin, nextcloud, sugarizer, usb_lib, wordpress, www_options.
#
# SEE ALSO: roles/nginx/README.md

- name: NGINX
  include_role:
    name: nginx
  when: nginx_install | bool

- name: WWW_BASE (WWW_OPTIONS should be installed later)
  include_role:
    name: www_base

- name: Recording STAGE 3 HAS COMPLETED =====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=3'
