- name: Make the directories to hold notebooks
  file:
    state: directory
    path: '{{ notebook_dir }}'

- name: Use pip to install into a virtual environment
  pip:
    name:
       - jupyterlab
       #- jupyter_vim
    virtualenv: "{{ jupyter_venv }}"    # /opt/iiab/jupyter
    virtualenv_site_packages: no
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: python3
    extra_args: "--no-cache-dir"
  when: internet_available
    
