- name: Make the directories to hold notebooks
  file:
    state: directory
    path: '{{ item }}'
  with_items:
     - '{{ notebook_dir }}/etc/jupyter'
     - '{{ notebook_dir }}/etc/jupyterhub'
     - '{{ notebook_dir }}/etc/systemd'

- name: Use pip to install into a virtual environment
  pip:
    name:
       - pip
       - wheel
       - ipywidgets
    virtualenv: "{{ jupyter_venv }}"    # /opt/iiab/jupyter
    virtualenv_site_packages: no
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: python3
    extra_args: "--no-cache-dir"
  when: internet_available
    
- name: Fetch the Littlest JupyterHub code
  ansible.builtin.git:
     repo: '{{ jupyterhub_url }} 
     dest: '{{ jupyter_venv }}'

- name: Install a bootstrap.py that permits installation on other than Ubunt
  template:
     src: bootstrap.py
     dest: '{{ jupyter_venv }}'
     
