- name: Install Jupyter if jupyter_installed not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: jupyter_installed is undefined


#- include_tasks: enable-or-disable.yml


- name: Add 'jupyter' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: jupyter
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Jupyter
    - option: description
      value: '"Raspberry Pi Jupyter python programming environment"'
    - option: install
      value: "{{ jupyter_install }}"
    - option: enabled
      value: "{{ jupyter_enabled }}"
