- name: Copy css files to /library/www/html/common/css
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/css"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/css/*.css

- name: Copy js files to /library/www/html/common/js
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/js"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/js/*.js

- name: Copy fonts files to /library/www/html/common/fonts
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/fonts"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/fonts/*

- name: Copy html files to /library/www/html/common/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/html"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/html/*

- name: Copy assets files to /library/www/html/common/assets
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/assets"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/assets/*

# copy all services, even if not permissioned elsewhere
- name: Copy services files to /library/www/html/common/services
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/services"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/services/*

- name: Create symlink from assets to /etc/iiab/iiab.ini
  file:
    src: "/etc/iiab/iiab.ini"
    dest: "{{ doc_root }}/common/assets/iiab.ini"
    owner: root
    group: root
    state: link
