- include_tasks: install.yml
- include_tasks: html.yml

# 2018-07-18: Partially fixes search @ http://box/modules/es-wikihow (on RPi
# anyway) https://github.com/iiab/iiab/issues/829 & PR #925
# 2020-01-23: Deprecated as @tim-moody's attempt to revive this for PHP 7.3
# instead of 7.0 failed: https://github.com/iiab/iiab/issues/2123
#- include_tasks: php-stem.yml

- name: Install /usr/bin/iiab-refresh-wiki-docs (scraper script) to create http://box/info offline documentation.  (Script can be run manually and/or at the end of Stage 4 = roles/4-server-options/tasks/main.yml)
  template:
    src: refresh-wiki-docs.sh
    dest: /usr/bin/iiab-refresh-wiki-docs
    mode: '0755'
