# Fixes search @ http://box/modules/es-wikihow - see https://github.com/iiab/iiab/issues/829

#- name: Download php-stem.rpi.tar
#  command: cd /; wget http://download.iiab.io/packages/php-stem.rpi.tar
#  when: is_rpi

#- name: Download php-stem.x86.tar
#  command: cd /; wget http://download.iiab.io/packages/php-stem.x64.tar
#  when: not is_rpi

- name: Download & unpack php-stem.rpi.tar to / (rpi)
  unarchive:
    src: http://download.iiab.io/packages/php-stem.rpi.tar
    dest: /
    remote_src: yes
  when: is_rpi

- name: Download & unpack php-stem.x86.tar to / (not rpi)
  unarchive:
    src: http://download.iiab.io/packages/php-stem.x64.tar
    dest: /
    remote_src: yes
  when: not is_rpi

- name: Restart Apache
  service:
    name: "{{ apache_service }}"
    state: restarted
