# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "lokole_install is sameas true" (boolean not string etc)
  assert:
    that: lokole_install is sameas true
    fail_msg: "PLEASE SET 'lokole_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "lokole_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: lokole_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'lokole_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- name: Install Lokole {{ lokole_version }} if lokole_installed is not defined
  include_tasks: install.yml
  when: lokole_installed is undefined


- name: Enable & Restart 'lokole' systemd service
  systemd:
    name: lokole
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: lokole_enabled | bool

- name: Disable & Stop 'lokole' systemd service
  systemd:
    name: lokole
    enabled: no
    state: stopped
  when: not lokole_enabled

#- name: Enable/Disable/Restart Apache if primary
- name: SHIM FOR NOW SO ALWAYS DO THE...Enable/Disable/Restart Apache
  include_tasks: apache.yml
  #when: not nginx_enabled

- name: Enable/Disable/Restart NGINX if primary
  include_tasks: nginx.yml
  when: nginx_enabled | bool


- name: Add 'lokole' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab_state.yml
    section: lokole
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: lokole
    - option: description
      value: '"Lokole is an email service that works offline, for rural communities."'
    - option: lokole_run_directory
      value: "{{ lokole_run_directory }}"
    - option: lokole_url
      value: "{{ lokole_url }}"
    - option: lokole_full_url
      value: "{{ lokole_full_url }}"
    - option: lokole_enabled
      value: "{{ lokole_enabled }}"
