- name: Install MediaWiki {{ mediawiki_version }}
  include_tasks: install.yml
  when: mediawiki_install and not mediawiki_installed is defined

- name: Enable MediaWiki
  include_tasks: enable.yml
  when: mediawiki_install or mediawiki_installed is defined
  # when: mediawiki_enabled | bool
