- name: Enable & Start 'munin-node' systemd service
  systemd:
    name: munin-node
    daemon_reload: yes
    enabled: yes
    state: started
  when: munin_enabled | bool

- name: Disable 'munin-node' systemd service
  systemd:
    name: munin-node
    enabled: no
    state: stopped
  when: not munin_enabled

# Apache

- name: Enable http://box/munin via Apache
  command: a2ensite munin24.conf
  when: apache_install and munin_enabled    # and not nginx_enabled

- name: Disable http://box/munin via Apache
  command: a2dissite munin24.conf
  when: apache_install and not munin_enabled    # or nginx_enabled

- name: Restart Apache systemd service ({{ apache_service }})
  systemd:
    name: "{{ apache_service }}"    # apache2 or httpd, as set in /opt/iiab/iiab/vars/<OS>.yml
    state: restarted
  when: apache_enabled | bool

# NGINX

- name: Enable http://box/munin via NGINX, by installing {{ nginx_config_dir }}/munin24-nginx.conf from template
  template:
    src: munin24-nginx.conf.j2
    dest: "{{ nginx_config_dir }}/munin24-nginx.conf"    # /etc/nginx/conf.d
  when: munin_enabled and nginx_enabled

- name: Disable http://box/munin via NGINX, by installing {{ nginx_config_dir }}/munin24-nginx.conf
  file:
    path: "{{ nginx_config_dir }}/munin24-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not munin_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
  when: nginx_enabled | bool


- name: Add 'munin' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: munin
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Munin
    - option: description
      value: '"Munin is a networked resource monitoring tool that can help analyze resource trends and \"what just happened to kill our performance?\" problems."'
    - option: installed
      value: "{{ munin_install }}"
    - option: enabled
      value: "{{ munin_enabled }}"
