- name: Ensure directory {{ vector_map_path }}/maplist/assets exists
  file:
    path: '{{ vector_map_path }}/maplist/assets'
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_user }}'
    mode: '0755'

- name: Fetch the catalog for osm maps
  get_url:
    url: "{{ iiab_map_url }}/assets/regions.json"
    dest: '{{ vector_map_path }}/maplist/assets/'

- name: Symlink catalog {{ doc_root }}/common/assets/regions.json -> {{ vector_map_path }}/maplist/assets/regions.json
  file:
    src: "{{ vector_map_path }}/maplist/assets/regions.json"
    dest: "{{ doc_root }}/common/assets/regions.json"
    state: link

- name: Fetch the JavaScript bundle with OpenLayers for test page http://box/maps/maplist
  get_url:
    url: "{{ iiab_map_url }}/../main.js"
    dest: '{{ vector_map_path }}/maplist/'

- name: Install index.html from template, for test page http://box/maps/maplist
  template:
    src: "index.html"
    dest: '{{ vector_map_path }}/maplist/index.html'

# Bboxes (bounding boxes) are currently square.  But geofabrik has non-rectangular bboxes.
# So bring the bounding box definition from cloud (bboxes.geojson is big)
- name: Fetch the bounding box description for osm maps
  get_url:
    url: "{{ iiab_map_url }}/assets/bboxes.geojson"
    dest: '{{ vector_map_path }}/maplist/assets/'

- name: Install python-geojson package, that helps with geojson
  package:
    name: python-geojson
    state: present

- name: Install the script to update osm catalog
  template:
    src: iiab-update-map
    dest: /usr/bin/iiab-update-map
    mode: "0755"

# This depends on iiab-admin-console which is not yet installed
#- name: Run the script that does osm-vector-maps housekeeping
#  shell: /usr/bin/iiab-update-map

- name: Copy countries.json (geojson) to {{ vector_map_path }}/maplist/assets
  copy:
    src: countries.json
    dest: '{{ vector_map_path }}/maplist/assets'

#  It is too complicated to use a single file for both iiab and admin-console
- name: Copy the duplicated JavaScript (map_functions.js) to {{ vector_map_path }}/maplist/assets
  copy:
    src: map_functions.js
    dest: '{{ vector_map_path }}/maplist/assets'

- name: Install /etc/{{ apache_config_dir }}/osm-vector-maps.conf from template
  template:
    src: osm-vector-maps.conf
    dest: "/etc/{{ apache_config_dir }}/osm-vector-maps.conf"

- name: Create symlink osm-vector-maps.conf from sites-enabled to sites-available (debuntu, not nec for redhat)
  file:
    src: /etc/apache2/sites-available/osm-vector-maps.conf
    path: /etc/apache2/sites-enabled/osm-vector-maps.conf
    state: link
  when: osm_vector_maps_enabled and is_debuntu

- name: Remove symlink /etc/apache2/sites-enabled/osm-vector-maps.conf (debuntu)
  file:
    path: /etc/apache2/sites-enabled/osm-vector-maps.conf
    state: absent
  when: not osm_vector_maps_enabled and is_debuntu

- name: Copy the redirect to the test page -- delete this if more than one map
  copy:
    src: test-index.redirect
    dest: "{{ vector_map_path }}/index.html"
