- name: Enable http://box/maps & http://box/osm-vector-maps via NGINX, by installing {{ nginx_conf_dir }}/osm-vector-maps-nginx.conf from template
  template:
    src: osm-vector-maps-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/osm-vector-maps-nginx.conf"    # /etc/nginx/conf.d
  when: osm_vector_maps_install | bool
# Note that the above change from enabled->install is required by the OSM command line installer

- name: Disable http://box/maps & http://box/osm-vector-maps via NGINX, by removing {{ nginx_conf_dir }}/osm-vector-maps-nginx.conf
  file:
    path: "{{ nginx_conf_dir }}/osm-vector-maps-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not osm_vector_maps_install

- name: Reload 'nginx' systemd service
  systemd:
    name: nginx
    state: reloaded
