# 2023-02-24: MONITOR FIRMWARE UPDATES in 3 places especially:
#
# 1. apt changelog firmware-brcm80211
#    https://github.com/RPi-Distro/firmware-nonfree
#    http://archive.raspberrypi.org/debian/dists/bullseye/main/binary-arm64/Packages
#    http://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_*
# 2. apt changelog linux-firmware-raspi
#    https://packages.ubuntu.com/search?keywords=linux-firmware-raspi
# 3. https://github.com/moodlebox/moodlebox/blob/main/roles/accesspoint/tasks/main.yml

#- name: Back up 4 OS-provided WiFi firmware files (incl symlink contents) to /lib/firmware/cypress/*.orig
- name: Back up 4 OS-provided WiFi firmware files (or preserve symlinks) to /lib/firmware/cypress/*.orig
  # copy:
  #   src: /lib/firmware/cypress/{{ item }}
  #   dest: /lib/firmware/cypress/{{ item }}.orig
  #   local_follow: False    # FAILS TO PRESERVE LINKS (ansible/ansible#74777) e.g. /lib/firmware/cypress/cyfmac43455-sdio.bin -> /etc/alternatives/cyfmac43455-sdio.bin -> ...
  command: cp -P /lib/firmware/cypress/{{ item }} /lib/firmware/cypress/{{ item }}.orig
  with_items:
    - cyfmac43430-sdio.bin
    - cyfmac43430-sdio.clm_blob
    - cyfmac43455-sdio.bin
    - cyfmac43455-sdio.clm_blob
  #ignore_errors: yes

- name: Download higher-capacity firmwares (for RPi internal WiFi, per https://github.com/iiab/iiab/issues/823#issuecomment-662285202 and https://github.com/iiab/iiab/issues/2853)
  get_url:
    url: "{{ iiab_download_url }}/{{ item }}"
    dest: /lib/firmware/cypress/
    timeout: "{{ download_timeout }}"
  with_items:
    - brcmfmac43455-sdio.bin_2021-11-30_minimal                # 19 -- SAME AS RASPIOS & UBUNTU'S https://github.com/RPi-Distro/firmware-nonfree/blob/feeeda21e930c2e182484e8e1269b61cca2a8451/debian/config/brcm80211/cypress/cyfmac43455-sdio-minimal.bin
    - brcmfmac43455-sdio.bin_2021-10-05_3rd-trial-minimal      # 24 -- from https://github.com/iiab/iiab/issues/2853#issuecomment-934293015
    - brcmfmac43455-sdio.clm_blob_2021-11-17_rpi               # Works w/ both above -- SAME AS RASPIOS & UBUNTU'S https://github.com/RPi-Distro/firmware-nonfree/blob/dc406650e840705957f8403efeacf71d2d7543b3/debian/config/brcm80211/cypress/cyfmac43455-sdio.clm_blob
    - brcmfmac43455-sdio.bin_2015-03-01_7.45.18.0_ub19.10.1    # 32 -- from https://github.com/iiab/iiab/issues/823#issuecomment-662285202
    - brcmfmac43455-sdio.clm_blob_2018-02-26_rpi
    - brcmfmac43430-sdio.bin_2018-09-11_7.45.98.65             # 30 -- from https://github.com/iiab/iiab/issues/823#issuecomment-662285202
    - brcmfmac43430-sdio.clm_blob_2018-09-11_7.45.98.65


# RECORD firmware AS DOWNLOADED

- name: "Set 'firmware_downloaded: True'"
  set_fact:
    firmware_downloaded: True

- name: "Add 'firmware_downloaded: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^firmware_downloaded'
    line: 'firmware_downloaded: True'

# SEE ALSO firmware_installed in install.yml
