# check the timestamps, might want to preserve the old ones
- name: Backup OS provided Firmware
  copy:
    src: "/lib/firmware/brcm/{{ item }}"
    dest: "/lib/firmware/brcm/{{ item }}.orig"
  with_items:
    - brcmfmac43430-sdio.bin
    - brcmfmac43455-sdio.bin
    - brcmfmac43455-sdio.clm_blob

# grab the old firmware
- name: Retrieve older firmware
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: 'http://d.iiab.io/packages/brcmfmac43430-sdio.clm_blob_2018-09-11_7.45.98.65', dest: '/lib/firmware/brcm/brcmfmac43430-sdio.clm_blob.iiab' }
    - { url: 'http://d.iiab.io/packages/brcmfmac43430-sdio.bin_2018-09-11_7.45.98.65', dest: '/lib/firmware/brcm/brcmfmac43430-sdio.bin.iiab' }
    - { url: 'http://d.iiab.io/packages/brcmfmac43455-sdio.bin_2015-03-01_7.45.18.0_ub19.10.1', dest: '/lib/firmware/brcm/brcmfmac43455-sdio.bin.iiab' }
    - { url: 'http://d.iiab.io/packages/brcmfmac43455-sdio.clm_blob_2018-02-26_rpi', dest: '/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob.iiab' }

- name: "Add 'firmware_retrieved: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^rpi_firmware_downloaded'
    line: 'rpi_firmware_downloaded: True'
