# Please set 'rpi3bplus_rpi4_wifi_firmware' and 'rpizerow_rpi3_wifi_firmware' in
# /etc/iiab/local_vars.yml to increase (or modify) the number of student WiFi
# client devices that can access your Raspberry Pi's internal WiFi hotspot.

# If IIAB's already installed, you should then run 'cd /opt/iiab/iiab'
# followed by 'sudo ./runrole firmware'

# Background: https://github.com/iiab/iiab/issues/823#issuecomment-662285202

- name: Install firmware (for RPi internal WiFi)
  include_tasks: install.yml
  #when: firmware_installed is undefined

# Two variables are placed in /etc/iiab/iiab_state.yml:
#
# - firmware_downloaded (set in download.yml) is used in install.yml
#
# - firmware_installed (set in install.yml) isn't acted upon programmatically.
#   It serves as a very helpful rapid reminder in iiab_state.yml in the same
#   way as roles like: sshd, iiab-admin, pylibs, www_base, www_options.
