- name: Back up/Download firmware (for RPi internal WiFi)
  include_tasks: install.yml
  when: rpi_firmware_downloaded is undefined

- name: 'Install from template: check-firmware.service, check-firmware.sh & fw_warn.sh'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'check-firmware.service', dest: '/etc/systemd/system/', mode: '0644' }
    - { src: 'check-firmware.sh', dest: '/usr/sbin/', mode: '0755' }
    - { src: 'fw_warn.sh', dest: '/etc/profile.d/', mode: '0644' }

- name: Enable & (Re)start check-firmware.service
  systemd:
    name: check-firmware.service
    daemon_reload: yes
    state: restarted
    enabled: yes
