- name: Include older RPi Firmware
  include_tasks: install.yml
  when: RPi_firmware_retrieved is undefined

- name: Install check-firmware service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'fw_warn.sh', dest: '/etc/profile.d/', mode: '0644' }
    - { src: 'check-firmware.service', dest: '/etc/systemd/system/', mode: '0644' }
    - { src: 'check-firmware.sh', dest: '/usr/sbin/', mode: '0755' }

- name: Enable and Start check-firmware.service
  systemd:
    name: check-firmware.service
    state: reloaded    
    enabled: yes
    status: started
