name: '"10 min" IIAB on Ubuntu 24.04 on x86-64'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up /opt/iiab/iiab
        run: |
          mkdir /opt/iiab
          mv $GITHUB_WORKSPACE /opt/iiab
          mkdir $GITHUB_WORKSPACE
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          sudo mkdir /etc/iiab
          sudo cp /opt/iiab/iiab/vars/local_vars_small.yml /etc/iiab/local_vars.yml
      - run: sudo /opt/iiab/iiab/scripts/ansible
      - run: sudo ./iiab-install
        working-directory: /opt/iiab/iiab
      - run: iiab-summary
      - run: cat /etc/iiab/iiab_state.yml
      - run: cat /opt/iiab/iiab/tests.unused/expected_state_small.yml
      - run: diff /etc/iiab/iiab_state.yml /opt/iiab/iiab/tests.unused/expected_state_small.yml
